/**
 * Offer Entity Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: offers
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { faker } from "@faker-js/faker";
import type { OfferEntity } from "@aegora/core/offers/models/index.js";
import { offersSchemas } from "@aegora/core/offers";
import { ulid } from "ulid";

// Domain prefix from OpenAPI spec info.x-domain
const DOMAIN_PREFIX = "offers";

export function createOffer(overrides: Partial<OfferEntity> = {}) {
  const raw = {
    id: overrides.id ?? `${DOMAIN_PREFIX}_${ulid().toLowerCase()}`,
    createdAt: overrides.createdAt ?? new Date().toISOString(),
    updatedAt: overrides.updatedAt ?? new Date().toISOString(),
    consentBasisPresent: overrides.consentBasisPresent ?? faker.datatype.boolean(),
    customerId: overrides.customerId ?? faker.string.uuid(),
    offerId: overrides.offerId ?? `ofr_${ulid().toLowerCase()}`,
    status: overrides.status ?? "ranked",
    ...overrides,
  };

  return offersSchemas.Offer.parse(raw);
}

export function offerBatch(n = 3, overrides = {}) {
  return Array.from({ length: n }, () => createOffer(overrides));
}
