/**
 * Dependency Container
 *
 * AUTO-GENERATED by codegen (api_server_domain_dependencies). Do not edit by hand.
 * Regenerate with: pnpm run codegen (domain list from platform/api-server/src/domains rescan).
 *
 * Manages dependency creation and caching per domain.
 */

import type { AdapterDynamoDBClient } from "@aegora/adapters";
import { getDynamoClientInstance } from "../lib/dependencies/domain-dependencies.js";
import { executionContextService } from "../lib/context/execution-context.service.js";
import {
  buildAlertsDomainModule,
  buildAuditsDomainModule,
  buildCasesDomainModule,
  buildEventsDomainModule,
  buildHoldsDomainModule,
  buildIdentityDomainModule,
  buildModelsDomainModule,
  buildOffersDomainModule,
  buildPoliciesDomainModule,
} from "../domains/index.js";
import type {
  AlertsDomainModule,
  AuditsDomainModule,
  CasesDomainModule,
  EventsDomainModule,
  HoldsDomainModule,
  IdentityDomainModule,
  ModelsDomainModule,
  OffersDomainModule,
  PoliciesDomainModule,
} from "../domains/index.js";

class DependencyContainer {
  private readonly dynamoClient: AdapterDynamoDBClient;

  private alertsModule: AlertsDomainModule | null = null;
  private auditsModule: AuditsDomainModule | null = null;
  private casesModule: CasesDomainModule | null = null;
  private eventsModule: EventsDomainModule | null = null;
  private holdsModule: HoldsDomainModule | null = null;
  private identityModule: IdentityDomainModule | null = null;
  private modelsModule: ModelsDomainModule | null = null;
  private offersModule: OffersDomainModule | null = null;
  private policiesModule: PoliciesDomainModule | null = null;

  constructor(dynamoClient: AdapterDynamoDBClient) {
    this.dynamoClient = dynamoClient;
  }

  /**
   * Get alerts domain module
   */
  getAlertsDependencies(): AlertsDomainModule {
    if (!this.alertsModule) {
      this.alertsModule = buildAlertsDomainModule(this.dynamoClient);
    }
    return this.alertsModule;
  }

  /**
   * Get audits domain module
   */
  getAuditsDependencies(): AuditsDomainModule {
    if (!this.auditsModule) {
      this.auditsModule = buildAuditsDomainModule(this.dynamoClient);
    }
    return this.auditsModule;
  }

  /**
   * Get cases domain module
   */
  getCasesDependencies(): CasesDomainModule {
    if (!this.casesModule) {
      this.casesModule = buildCasesDomainModule(this.dynamoClient);
    }
    return this.casesModule;
  }

  /**
   * Get events domain module
   */
  getEventsDependencies(): EventsDomainModule {
    if (!this.eventsModule) {
      this.eventsModule = buildEventsDomainModule(this.dynamoClient);
    }
    return this.eventsModule;
  }

  /**
   * Get holds domain module
   */
  getHoldsDependencies(): HoldsDomainModule {
    if (!this.holdsModule) {
      this.holdsModule = buildHoldsDomainModule(this.dynamoClient);
    }
    return this.holdsModule;
  }

  /**
   * Get identity domain module
   */
  getIdentityDependencies(): IdentityDomainModule {
    if (!this.identityModule) {
      this.identityModule = buildIdentityDomainModule(this.dynamoClient);
    }
    return this.identityModule;
  }

  /**
   * Get models domain module
   */
  getModelsDependencies(): ModelsDomainModule {
    if (!this.modelsModule) {
      this.modelsModule = buildModelsDomainModule(this.dynamoClient);
    }
    return this.modelsModule;
  }

  /**
   * Get offers domain module
   */
  getOffersDependencies(): OffersDomainModule {
    if (!this.offersModule) {
      this.offersModule = buildOffersDomainModule(this.dynamoClient);
    }
    return this.offersModule;
  }

  /**
   * Get policies domain module
   */
  getPoliciesDependencies(): PoliciesDomainModule {
    if (!this.policiesModule) {
      this.policiesModule = buildPoliciesDomainModule(this.dynamoClient);
    }
    return this.policiesModule;
  }

  clearAlertsDependencies(): void { this.alertsModule = null; }
  clearAuditsDependencies(): void { this.auditsModule = null; }
  clearCasesDependencies(): void { this.casesModule = null; }
  clearEventsDependencies(): void { this.eventsModule = null; }
  clearHoldsDependencies(): void { this.holdsModule = null; }
  clearIdentityDependencies(): void { this.identityModule = null; }
  clearModelsDependencies(): void { this.modelsModule = null; }
  clearOffersDependencies(): void { this.offersModule = null; }
  clearPoliciesDependencies(): void { this.policiesModule = null; }

  getAlertsDependenciesForRequest(): AlertsDomainModule {
    return this.getAlertsDependencies();
  }

  getAuditsDependenciesForRequest(): AuditsDomainModule {
    return this.getAuditsDependencies();
  }

  getCasesDependenciesForRequest(): CasesDomainModule {
    return this.getCasesDependencies();
  }

  getEventsDependenciesForRequest(): EventsDomainModule {
    return this.getEventsDependencies();
  }

  getHoldsDependenciesForRequest(): HoldsDomainModule {
    return this.getHoldsDependencies();
  }

  getIdentityDependenciesForRequest(): IdentityDomainModule {
    return this.getIdentityDependencies();
  }

  getModelsDependenciesForRequest(): ModelsDomainModule {
    return this.getModelsDependencies();
  }

  getOffersDependenciesForRequest(): OffersDomainModule {
    return this.getOffersDependencies();
  }

  getPoliciesDependenciesForRequest(): PoliciesDomainModule {
    return this.getPoliciesDependencies();
  }

  /**
   * Clear all caches
   */
  clearAllCaches(): void {
    this.alertsModule = null;
    this.auditsModule = null;
    this.casesModule = null;
    this.eventsModule = null;
    this.holdsModule = null;
    this.identityModule = null;
    this.modelsModule = null;
    this.offersModule = null;
    this.policiesModule = null;
  }
}

let dependencyContainerInstance: DependencyContainer | null = null;

export function getDependencyContainer(): DependencyContainer {
  if (!dependencyContainerInstance) {
    const dynamoClient = getDynamoClientInstance();
    dependencyContainerInstance = new DependencyContainer(dynamoClient);
  }
  return dependencyContainerInstance;
}
