/**
 * CreateOffer handler tests
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: offers
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { describe, it, expect, beforeEach, vi } from "vitest";
import { createOffer } from "@aegora/api-server/domains/offers/handlers";
import type { OffersDDDDependencies } from "@aegora/api-server/domains/offers";
import { createOffer as createOfferEntity } from "@aegora/factories/offers";
import { createMockRequest, createMockReply, createMockDependencies, TEST_ORG_ID } from "@aegora/tests/shared";
import { OFFERS_USE_CASES } from "../__factories__/use-cases.js";

describe("CreateOffer", () => {
  let mockRequest: ReturnType<typeof createMockRequest>;
  let mockReply: ReturnType<typeof createMockReply>;
  let mockDeps: OffersDDDDependencies;
  const orgId = TEST_ORG_ID;

  beforeEach(() => {
    mockRequest = createMockRequest({ orgId });
    mockReply = createMockReply();
    mockDeps = createMockDependencies<OffersDDDDependencies>(
      OFFERS_USE_CASES,
      {
        // Mock use case dependencies here
      }
    );
  });

  it("should return 201 with created entity", async () => {
    const input = {} as any;
    const entity = createOfferEntity({ orgId });
    const useCaseResult = { data: entity, meta: { correlationId: "test", timestamp: new Date().toISOString() } };
    
    mockRequest.body = input;
    vi.spyOn(mockDeps.executeCreateOffer, "execute").mockResolvedValue(useCaseResult);

    await createOffer(mockRequest, mockReply, mockDeps);

    expect(mockDeps.executeCreateOffer.execute).toHaveBeenCalledWith(expect.anything());
    expect(mockReply.code).toHaveBeenCalledWith(201);
    expect(mockReply.send).toHaveBeenCalledWith(useCaseResult);
  });

});
