/**
 * Handlers for Event
 *
 * Generated by Handler Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: events
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyRequest, FastifyReply } from "fastify";
import type { EventsDomainModule } from "../dependencies/events-ddd.dependencies.js";
import type { GetEventInput, IngestEventInput, ListEventsInput } from "@aegora/services/events";
// Use cases are available via deps.useCases.<repoKey>.<verb>
// Execution context is automatically set up by route wrapper (wrapHandlerInExecutionContext)

/**
 * Handler for GET /v1/events
 * Operation: listEvents
 */
export async function listEvents(
  request: FastifyRequest<{ Params: Record<string, string>; Querystring: { cursor?: string | string[], limit?: string | string[], customerId?: string | string[], purpose?: string | string[] }; Body: unknown }>,
  reply: FastifyReply,
  deps: EventsDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: ListEventsInput = {
    ...(request.query ?? {}),
  };
  const result = await deps.useCases.events.list.execute(input);
  return reply.code(200).send(result);
}


/**
 * Handler for POST /v1/events
 * Operation: ingestEvent
 */
export async function ingestEvent(
  request: FastifyRequest,
  reply: FastifyReply,
  deps: EventsDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: IngestEventInput = {
    ...(request.body ?? {}),
  };
  const result = await deps.useCases.events.get.execute(input);
  return reply.code(200).send(result);
}


/**
 * Handler for GET /v1/events/{eventId}
 * Operation: getEvent
 */
export async function getEvent(
  request: FastifyRequest<{ Params: { eventId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>,
  reply: FastifyReply,
  deps: EventsDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: GetEventInput = {
    eventId: request.params.eventId,
  };
  const result = await deps.useCases.events.get.execute(input);
  return reply.code(200).send(result);
}


