/**
 * ListHold DTO Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: holds
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import type { ListHoldsParams } from "@aegora/core/holds";

export function createListHoldRequest(overrides: Partial<ListHoldsParams> = {}) {
  const raw = {
    ...overrides,
  };

  return raw;
}
