/**
 * Assign DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: cases
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Assign DTOs
 *
 * DDD: Application DTOs for Assign use cases.
 */

import type { AssignCaseParams, AssignCaseRequestInput } from "@aegora/core/cases/types";

export type AssignCaseInput = AssignCaseParams & AssignCaseRequestInput;

export type AssignCaseOutput = {};
