/**
 * Close DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: cases
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Close DTOs
 *
 * DDD: Application DTOs for Close use cases.
 */

import type { CloseCaseParams, CloseCaseRequestInput } from "@aegora/core/cases/types";

export type CloseCaseInput = CloseCaseParams & CloseCaseRequestInput;

export type CloseCaseOutput = {};
