/**
 * DisputeRepository - DynamoDB Implementation
 *
 * Generated by DynamoDB Repository Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: holds
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * DisputeRepositoryDdb
 *
 * DDD: Infrastructure adapter for Dispute repository.
 * ⚠️  Missing x-dynamodb metadata - implementation not generated.
 */

import type { DisputeRepository } from "@aegora/services/holds";

export class DisputeRepositoryDdb implements DisputeRepository {
  constructor(private readonly dynamoClient: any) {}

  async listHoldDisputes(input: Parameters<DisputeRepository['listHoldDisputes']>[0]): Promise<Awaited<ReturnType<DisputeRepository['listHoldDisputes']>>> {
    // TODO: Implement using x-dynamodb metadata
    throw new Error("Not implemented - missing x-dynamodb metadata");
  }

  async createHoldDispute(input: Parameters<DisputeRepository['createHoldDispute']>[0]): Promise<Awaited<ReturnType<DisputeRepository['createHoldDispute']>>> {
    // TODO: Implement using x-dynamodb metadata
    throw new Error("Not implemented - missing x-dynamodb metadata");
  }
}
