/**
 * Policies DDD Dependencies - Composition root
 *
 * Generated by Dependencies Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: policies
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Policies Domain Module - Composition root
 *
 * DDD: Composition root for policies domain. Exposes repos (ports) and use cases
 * grouped by aggregate. No orgId at build time — use execution context at call time.
 */

import {
  ApproveRepositoryAdapter,
  DisableRepositoryAdapter,
  PolicyRepositoryAdapter,
} from "@aegora/adapters/policies";
import { getIdGeneratorService } from "@aegora/adapters";
import type { AdapterDynamoDBClient } from "@aegora/adapters";
import { executionContextService } from "../../../lib/execution-context.service.js";
// Use-case constructors (concrete)
import {
  ExecuteApprovePolicy,
  ExecuteCreatePolicy,
  ExecuteDisablePolicy,
  ExecuteGetPolicy,
  ExecuteListPolicies,
} from "@aegora/services/policies/usecases";
// Ports (interfaces)
import type {
  ApproveRepository,
  DisableRepository,
  PolicyRepository,
} from "@aegora/services/policies/ports";

export interface PoliciesDomainModule {
  repos: {
    approves: ApproveRepository;
    disables: DisableRepository;
    policies: PolicyRepository;
  };
  useCases: {
    approves: {
      create: ExecuteApprovePolicy;
    };
    disables: {
      update: ExecuteDisablePolicy;
    };
    policies: {
      create: ExecuteCreatePolicy;
      get: ExecuteGetPolicy;
      list: ExecuteListPolicies;
    };
  };
}

export function buildPoliciesDomainModule(
  dynamoClient: AdapterDynamoDBClient,
): PoliciesDomainModule {
  // Adapters implementing ports (adapters encapsulate Ddb)
  const repos = (() => {
    const obj: {
      approves?: ApproveRepository;
      disables?: DisableRepository;
      policies?: PolicyRepository;
    } = {};

    obj.approves = new ApproveRepositoryAdapter(dynamoClient);
    obj.disables = new DisableRepositoryAdapter(dynamoClient);
    obj.policies = new PolicyRepositoryAdapter(dynamoClient);
    return {
      approves: obj.approves!,
      disables: obj.disables!,
      policies: obj.policies!,
    };
  })();

  const executionContext = executionContextService;
  const idGenerator = getIdGeneratorService();

  // Use cases depend only on ports (repos.*)
  const useCases = {
    approves: {
      create: new ExecuteApprovePolicy(executionContext, idGenerator, repos.approves),
    },
    disables: {
      update: new ExecuteDisablePolicy(executionContext, idGenerator, repos.disables),
    },
    policies: {
      create: new ExecuteCreatePolicy(executionContext, idGenerator, repos.policies),
      get: new ExecuteGetPolicy(executionContext, idGenerator, repos.policies),
      list: new ExecuteListPolicies(executionContext, idGenerator, repos.policies),
    },
  };
  return { repos, useCases: useCases as PoliciesDomainModule["useCases"] };
}
