/**
 * Routes index
 *
 * Generated by Routes Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: policies
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

export { approveRoutes } from "./approve.routes.js";
export { disableRoutes } from "./disable.routes.js";
export { policyRoutes } from "./policy.routes.js";
