/**
 * Dispute Entity Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: holds
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import type { DisputeEntity } from "@aegora/core/holds/models/index.js";
import { holdsSchemas } from "@aegora/core/holds";
import { ulid } from "ulid";

// Domain prefix from OpenAPI spec info.x-domain
const DOMAIN_PREFIX = "holds";

export function createDispute(overrides: Partial<DisputeEntity> = {}) {
  const raw = {
    id: overrides.id ?? `${DOMAIN_PREFIX}_${ulid().toLowerCase()}`,
    createdAt: overrides.createdAt ?? new Date().toISOString(),
    updatedAt: overrides.updatedAt ?? new Date().toISOString(),
    disputeId: overrides.disputeId ?? `dsp_${ulid().toLowerCase()}`,
    holdId: overrides.holdId ?? `hld_${ulid().toLowerCase()}`,
    status: overrides.status ?? "open",
    ...overrides,
  };

  return holdsSchemas.Dispute.parse(raw);
}

export function disputeBatch(n = 3, overrides = {}) {
  return Array.from({ length: n }, () => createDispute(overrides));
}
