/**
 * ExecuteCreateAlert - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: alerts
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteCreateAlert Use Case
 *
 * DDD: Application use case for create Alert.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { CreateAlertInput, CreateAlertOutput } from "../dto/alert.dto";
import type { ExecutionContextService, IdGeneratorService } from "@aegora/services/_shared/index.js";
import type { AlertRepository } from "../ports";
import { PermissionDeniedError, ValidationError } from "../errors";
import { CanCreate } from "../policies/can-create.policy";
export class ExecuteCreateAlert {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly alert: AlertRepository
  ) {}

  async execute(input: CreateAlertInput): Promise<CreateAlertOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.alertsId();

    // All field names extracted from OpenAPI spec: alertId, alertType, clusterCentroid, convexHull, createdAt, customerId, priorVenues, raisedAt, severity, slaBreached, slaDeadlineAt, status, updatedAt
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!input.customerId) {
      throw new ValidationError("customerId is required");
    }
    if (!input.createdAt) {
      throw new ValidationError("createdAt is required");
    }
    if (!input.status) {
      throw new ValidationError("status is required");
    }
    if (!input.alertId) {
      throw new ValidationError("alertId is required");
    }
    if (!input.raisedAt) {
      throw new ValidationError("raisedAt is required");
    }    // Check policy
    if (!CanCreate.allow({} as any, "")) {
      throw new PermissionDeniedError("Operation not allowed");
    }

    // Generate entity ID in services layer using IdGeneratorService (alerts domain)
    const entityId = this.idGenerator.alertsId();

    // Create entity via repository (pass ID and correlation ID for response meta)
    const entity = await this.alert.createAlert({ ...input, id: entityId, createdByActorId: (input as any).createdByActorId ?? this.context.getUserId(), createdByActorType: (input as any).createdByActorType ?? "human", orgId: this.context.getOrgId(), correlationId } as any);

    return entity as CreateAlertOutput;
  }
}
