/**
 * BlockRepository - DynamoDB Implementation
 *
 * Generated by DynamoDB Repository Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: offers
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * BlockRepositoryDdb
 *
 * DDD: Infrastructure adapter for Block repository.
 * ⚠️  Missing x-dynamodb metadata - implementation not generated.
 */

import type { BlockRepository } from "@aegora/services/offers";

export class BlockRepositoryDdb implements BlockRepository {
  constructor(private readonly dynamoClient: any) {}

  async blockOffer(input: Parameters<BlockRepository['blockOffer']>[0]): Promise<Awaited<ReturnType<BlockRepository['blockOffer']>>> {
    // TODO: Implement using x-dynamodb metadata
    throw new Error("Not implemented - missing x-dynamodb metadata");
  }
}
