/**
 * BlockRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: offers
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * BlockRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements BlockRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  BlockRepository,
} from "@aegora/services/offers";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { BlockRepositoryDdb } from "./block-repository.ddb.js";

/**
 * BlockRepositoryAdapter
 *
 * Implements BlockRepository port for infrastructure layer.
 */
export class BlockRepositoryAdapter implements BlockRepository {
  private readonly ddb: BlockRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new BlockRepositoryDdb(this.dynamoClient);
  }

  async blockOffer(input: Parameters<BlockRepository['blockOffer']>[0]): Promise<Awaited<ReturnType<BlockRepository['blockOffer']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.blockOffer(input);
  }
}
