/**
 * ConsentRecordRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: offers
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ConsentRecordRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements ConsentRecordRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  ConsentRecordRepository,
} from "@aegora/services/offers";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { ConsentRecordRepositoryDdb } from "./consent-record-repository.ddb.js";

/**
 * ConsentRecordRepositoryAdapter
 *
 * Implements ConsentRecordRepository port for infrastructure layer.
 */
export class ConsentRecordRepositoryAdapter implements ConsentRecordRepository {
  private readonly ddb: ConsentRecordRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new ConsentRecordRepositoryDdb(this.dynamoClient);
  }

  async listConsentRecords(input: Parameters<ConsentRecordRepository['listConsentRecords']>[0]): Promise<Awaited<ReturnType<ConsentRecordRepository['listConsentRecords']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.listConsentRecords(input);
  }

  async createConsentRecord(input: Parameters<ConsentRecordRepository['createConsentRecord']>[0]): Promise<Awaited<ReturnType<ConsentRecordRepository['createConsentRecord']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.createConsentRecord(input);
  }
}
