/**
 * ConsentRecordRepository - DynamoDB Implementation
 *
 * Generated by DynamoDB Repository Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: offers
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ConsentRecordRepositoryDdb
 *
 * DDD: Infrastructure adapter for ConsentRecord repository.
 * ⚠️  Missing x-dynamodb metadata - implementation not generated.
 */

import type { ConsentRecordRepository } from "@aegora/services/offers";

export class ConsentRecordRepositoryDdb implements ConsentRecordRepository {
  constructor(private readonly dynamoClient: any) {}

  async listConsentRecords(input: Parameters<ConsentRecordRepository['listConsentRecords']>[0]): Promise<Awaited<ReturnType<ConsentRecordRepository['listConsentRecords']>>> {
    // TODO: Implement using x-dynamodb metadata
    throw new Error("Not implemented - missing x-dynamodb metadata");
  }

  async createConsentRecord(input: Parameters<ConsentRecordRepository['createConsentRecord']>[0]): Promise<Awaited<ReturnType<ConsentRecordRepository['createConsentRecord']>>> {
    // TODO: Implement using x-dynamodb metadata
    throw new Error("Not implemented - missing x-dynamodb metadata");
  }
}
