/**
 * DeliverRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: offers
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * DeliverRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements DeliverRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  DeliverRepository,
} from "@aegora/services/offers";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { DeliverRepositoryDdb } from "./deliver-repository.ddb.js";

/**
 * DeliverRepositoryAdapter
 *
 * Implements DeliverRepository port for infrastructure layer.
 */
export class DeliverRepositoryAdapter implements DeliverRepository {
  private readonly ddb: DeliverRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new DeliverRepositoryDdb(this.dynamoClient);
  }

  async deliverOffer(input: Parameters<DeliverRepository['deliverOffer']>[0]): Promise<Awaited<ReturnType<DeliverRepository['deliverOffer']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.deliverOffer(input);
  }
}
