/**
 * DynamoDB repository adapters barrel export
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: offers
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

export * from "./block-repository.ddb.js";
export * from "./consent-record-repository.ddb.js";
export * from "./deliver-repository.ddb.js";
export * from "./offer-repository.ddb.js";
export * from "./override-repository.ddb.js";
export * from "./block-repository.adapter.js";
export * from "./consent-record-repository.adapter.js";
export * from "./deliver-repository.adapter.js";
export * from "./offer-repository.adapter.js";
export * from "./override-repository.adapter.js";
