/**
 * OfferRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: offers
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * OfferRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements OfferRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  OfferRepository,
} from "@aegora/services/offers";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { OfferRepositoryDdb } from "./offer-repository.ddb.js";

/**
 * OfferRepositoryAdapter
 *
 * Implements OfferRepository port for infrastructure layer.
 */
export class OfferRepositoryAdapter implements OfferRepository {
  private readonly ddb: OfferRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new OfferRepositoryDdb(this.dynamoClient);
  }

  async listOffers(input: Parameters<OfferRepository['listOffers']>[0]): Promise<Awaited<ReturnType<OfferRepository['listOffers']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.listOffers(input);
  }

  async createOffer(input: Parameters<OfferRepository['createOffer']>[0]): Promise<Awaited<ReturnType<OfferRepository['createOffer']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.createOffer(input);
  }

  async getOffer(input: Parameters<OfferRepository['getOffer']>[0]): Promise<Awaited<ReturnType<OfferRepository['getOffer']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.getOffer(input);
  }
}
