/**
 * OverrideRepository - DynamoDB Implementation
 *
 * Generated by DynamoDB Repository Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: offers
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * OverrideRepositoryDdb
 *
 * DDD: Infrastructure adapter for Override repository.
 * ⚠️  Missing x-dynamodb metadata - implementation not generated.
 */

import type { OverrideRepository } from "@aegora/services/offers";

export class OverrideRepositoryDdb implements OverrideRepository {
  constructor(private readonly dynamoClient: any) {}

  async listOfferOverrides(input: Parameters<OverrideRepository['listOfferOverrides']>[0]): Promise<Awaited<ReturnType<OverrideRepository['listOfferOverrides']>>> {
    // TODO: Implement using x-dynamodb metadata
    throw new Error("Not implemented - missing x-dynamodb metadata");
  }

  async overrideOffer(input: Parameters<OverrideRepository['overrideOffer']>[0]): Promise<Awaited<ReturnType<OverrideRepository['overrideOffer']>>> {
    // TODO: Implement using x-dynamodb metadata
    throw new Error("Not implemented - missing x-dynamodb metadata");
  }
}
