/**
 * EventRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: events
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * EventRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements EventRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  EventRepository,
} from "@aegora/services/events";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { EventRepositoryDdb } from "./event-repository.ddb.js";

/**
 * EventRepositoryAdapter
 *
 * Implements EventRepository port for infrastructure layer.
 */
export class EventRepositoryAdapter implements EventRepository {
  private readonly ddb: EventRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new EventRepositoryDdb(this.dynamoClient);
  }

  async listEvents(input: Parameters<EventRepository['listEvents']>[0]): Promise<Awaited<ReturnType<EventRepository['listEvents']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.listEvents(input);
  }

  async ingestEvent(input: Parameters<EventRepository['ingestEvent']>[0]): Promise<Awaited<ReturnType<EventRepository['ingestEvent']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.ingestEvent(input);
  }

  async getEvent(input: Parameters<EventRepository['getEvent']>[0]): Promise<Awaited<ReturnType<EventRepository['getEvent']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.getEvent(input);
  }
}
