/**
 * Use Case List
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: holds
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


/**
 * Holds Domain Use Cases
 * 
 * List of all use case names for the holds domain.
 * Used by createMockDependencies() to pre-create mocks.
 */

export const HOLDS_USE_CASES = [
  "executeConfirmHold",
  "executeCreateHold",
  "executeCreateHoldDispute",
  "executeGetHold",
  "executeListHoldDisputes",
  "executeListHolds",
  "executeReleaseHold",
  "executeResolveDispute"
] as const;
