/**
 * Repository interface for ConsentRecord
 *
 * Generated by Repository Generator v1.0.0
 * Generator Version: 2.0.0
 * Domain: offers
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type {
  CreateReadRepository,
} from "../../_shared/repositories/_base-repository.js";

import type {
  ConsentRecordEntity
} from "../models/consent-record.entity.js";
import type {
  ListConsentRecordsParams,
  ConsentRecord
} from "../types/index.js";
/**
 * ConsentRecordRepository Interface
 */
export interface ConsentRecordRepository extends CreateReadRepository<ConsentRecordEntity, ConsentRecord, string, ListConsentRecordsParams> {

}
