/**
 * Repository interface for Offer
 *
 * Generated by Repository Generator v1.0.0
 * Generator Version: 2.0.0
 * Domain: offers
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type {
  CreateReadRepository,
} from "../../_shared/repositories/_base-repository.js";

import type {
  OfferEntity
} from "../models/offer.entity.js";
import type {
  ListOffersParams,
  Offer
} from "../types/index.js";
/**
 * OfferRepository Interface
 */
export interface OfferRepository extends CreateReadRepository<OfferEntity, Offer, string, ListOffersParams> {

}
