/**
 * ExecuteDeliverOffer - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: offers
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteDeliverOffer Use Case
 *
 * DDD: Application use case for get Deliver.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { DeliverOfferInput, DeliverOfferOutput } from "../dto/deliver.dto";
import type { ExecutionContextService, IdGeneratorService } from "@aegora/services/_shared/index.js";
import type { DeliverRepository } from "../ports";
import { NotFoundError, ValidationError } from "../errors";

export class ExecuteDeliverOffer {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly deliver: DeliverRepository
  ) {}

  async execute(input: DeliverOfferInput): Promise<DeliverOfferOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.offersId();

    // All field names extracted from OpenAPI spec: channel
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!(input as any).offerId) {
      throw new ValidationError("offerId is required");
    }
    const offerId = (input as any).offerId;

    // Load entity via repository (pass correlation ID for response meta)
    const entity = await this.deliver.deliverOffer({ offerId: offerId, orgId: this.context.getOrgId(), correlationId } as any);
    if (!entity) {
      throw new NotFoundError(`Entity not found: ${offerId}`);
    }

    return entity as DeliverOfferOutput;
  }
}
