/**
 * ExecuteListConsentRecords - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: offers
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteListConsentRecords Use Case
 *
 * DDD: Application use case for list ConsentRecord.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { ListConsentRecordsInput, ListConsentRecordsOutput } from "../dto/consent-record.dto";
import type { ExecutionContextService, IdGeneratorService } from "@aegora/services/_shared/index.js";
import type { ConsentRecordRepository } from "../ports";

export class ExecuteListConsentRecords {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly consentRecord: ConsentRecordRepository
  ) {}

  async execute(input: ListConsentRecordsInput): Promise<ListConsentRecordsOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.offersId();

    // All field names extracted from OpenAPI spec: none
    // List entities via repository
    const result = await this.consentRecord.listConsentRecords({ ...input, orgId: this.context.getOrgId(), correlationId } as any);

    return result as ListConsentRecordsOutput;
  }
}
