/**
 * ExecuteOpenCase - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: cases
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteOpenCase Use Case
 *
 * DDD: Application use case for get Case.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { OpenCaseInput, OpenCaseOutput } from "../dto/case.dto";
import type { ExecutionContextService, IdGeneratorService } from "@aegora/services/_shared/index.js";
import type { CaseRepository } from "../ports";
import { NotFoundError, ValidationError } from "../errors";

export class ExecuteOpenCase {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly caseRepo: CaseRepository
  ) {}

  async execute(input: OpenCaseInput): Promise<OpenCaseOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.casesId();

    // All field names extracted from OpenAPI spec: alertId, hostIds, summary
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!(input as any).alertId) {
      throw new ValidationError("alertId is required");
    }
    const alertId = (input as any).alertId;

    // Load entity via repository (pass correlation ID for response meta)
    const entity = await this.caseRepo.openCase({ alertId: alertId, orgId: this.context.getOrgId(), correlationId } as any);
    if (!entity) {
      throw new NotFoundError(`Entity not found: ${alertId}`);
    }

    return entity as OpenCaseOutput;
  }
}
