/**
 * BlockRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: offers
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * BlockRepository Port
 *
 * DDD: Application port for blockrepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { BlockOfferInput, BlockOfferOutput } from "../dto/block.dto";
export interface BlockRepository {
  blockOffer(input: BlockOfferInput): Promise<BlockOfferOutput>;
}

export type { BlockOfferInput, BlockOfferOutput } from "../dto/block.dto";
