/**
 * DeliverRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: offers
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * DeliverRepository Port
 *
 * DDD: Application port for deliverrepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { DeliverOfferInput, DeliverOfferOutput } from "../dto/deliver.dto";
export interface DeliverRepository {
  deliverOffer(input: DeliverOfferInput): Promise<DeliverOfferOutput>;
}

export type { DeliverOfferInput, DeliverOfferOutput } from "../dto/deliver.dto";
