/**
 * OfferRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: offers
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * OfferRepository Port
 *
 * DDD: Application port for offerrepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { CreateOfferInput, CreateOfferOutput, GetOfferInput, GetOfferOutput, ListOffersInput, ListOffersOutput } from "../dto/offer.dto";
export interface OfferRepository {
  listOffers(input: ListOffersInput): Promise<ListOffersOutput>;
  createOffer(input: CreateOfferInput): Promise<CreateOfferOutput>;
  getOffer(input: GetOfferInput): Promise<GetOfferOutput>;
}

export type { CreateOfferInput, CreateOfferOutput, GetOfferInput, GetOfferOutput, ListOffersInput, ListOffersOutput } from "../dto/offer.dto";
