/**
 * GetAlert DTO Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: alerts
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import type { GetAlertParams } from "@aegora/core/alerts";

export function createGetAlertRequest(overrides: Partial<GetAlertParams> = {}) {
  const raw = {
    ...overrides,
  };

  return raw;
}
