/**
 * ConsentRecord Entity Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: offers
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { faker } from "@faker-js/faker";
import type { ConsentRecordEntity } from "@aegora/core/offers/models/index.js";
import { offersSchemas } from "@aegora/core/offers";
import { ulid } from "ulid";

// Domain prefix from OpenAPI spec info.x-domain
const DOMAIN_PREFIX = "offers";

export function createConsentRecord(overrides: Partial<ConsentRecordEntity> = {}) {
  const raw = {
    id: overrides.id ?? `${DOMAIN_PREFIX}_${ulid().toLowerCase()}`,
    createdAt: overrides.createdAt ?? new Date().toISOString(),
    updatedAt: overrides.updatedAt ?? new Date().toISOString(),
    basisPresent: overrides.basisPresent ?? faker.datatype.boolean(),
    consentRecordId: overrides.consentRecordId ?? `cns_${ulid().toLowerCase()}`,
    customerId: overrides.customerId ?? faker.string.uuid(),
    purpose: overrides.purpose ?? "help",
    ...overrides,
  };

  return offersSchemas.ConsentRecord.parse(raw);
}

export function consentRecordBatch(n = 3, overrides = {}) {
  return Array.from({ length: n }, () => createConsentRecord(overrides));
}
