/**
 * ExecuteResolveDispute - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: holds
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteResolveDispute Use Case
 *
 * DDD: Application use case for get Resolve.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { ResolveDisputeInput, ResolveDisputeOutput } from "../dto/resolve.dto";
import type { ExecutionContextService, IdGeneratorService } from "@aegora/services/_shared/index.js";
import type { ResolveRepository } from "../ports";
import { NotFoundError, ValidationError } from "../errors";

export class ExecuteResolveDispute {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly resolve: ResolveRepository
  ) {}

  async execute(input: ResolveDisputeInput): Promise<ResolveDisputeOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.holdsId();

    // All field names extracted from OpenAPI spec: resolution, restoreService
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!(input as any).disputeId) {
      throw new ValidationError("disputeId is required");
    }
    const disputeId = (input as any).disputeId;

    // Load entity via repository (pass correlation ID for response meta)
    const entity = await this.resolve.resolveDispute({ disputeId: disputeId, orgId: this.context.getOrgId(), correlationId } as any);
    if (!entity) {
      throw new NotFoundError(`Entity not found: ${disputeId}`);
    }

    return entity as ResolveDisputeOutput;
  }
}
