/**
 * ExecuteListHolds - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: holds
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteListHolds Use Case
 *
 * DDD: Application use case for list Hold.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { ListHoldsInput, ListHoldsOutput } from "../dto/hold.dto";
import type { ExecutionContextService, IdGeneratorService } from "@aegora/services/_shared/index.js";
import type { HoldRepository } from "../ports";

export class ExecuteListHolds {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly hold: HoldRepository
  ) {}

  async execute(input: ListHoldsInput): Promise<ListHoldsOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.holdsId();

    // All field names extracted from OpenAPI spec: none
    // List entities via repository
    const result = await this.hold.listHolds({ ...input, orgId: this.context.getOrgId(), correlationId } as any);

    return result as ListHoldsOutput;
  }
}
