/**
 * ExecuteConfirmHold - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: holds
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteConfirmHold Use Case
 *
 * DDD: Application use case for get Confirm.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { ConfirmHoldInput, ConfirmHoldOutput } from "../dto/confirm.dto";
import type { ExecutionContextService, IdGeneratorService } from "@aegora/services/_shared/index.js";
import type { ConfirmRepository } from "../ports";
import { NotFoundError, ValidationError } from "../errors";

export class ExecuteConfirmHold {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly confirm: ConfirmRepository
  ) {}

  async execute(input: ConfirmHoldInput): Promise<ConfirmHoldOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.holdsId();

    // All field names extracted from OpenAPI spec: none
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!(input as any).holdId) {
      throw new ValidationError("holdId is required");
    }
    const holdId = (input as any).holdId;

    // Load entity via repository (pass correlation ID for response meta)
    const entity = await this.confirm.confirmHold({ holdId: holdId, orgId: this.context.getOrgId(), correlationId } as any);
    if (!entity) {
      throw new NotFoundError(`Entity not found: ${holdId}`);
    }

    return entity as ConfirmHoldOutput;
  }
}
