/**
 * Disable DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: policies
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Disable DTOs
 *
 * DDD: Application DTOs for Disable use cases.
 */

import type { DisablePolicyParams } from "@aegora/core/policies/types";

export type DisablePolicyInput = DisablePolicyParams;

export type DisablePolicyOutput = {};
