/**
 * Cases DDD Dependencies - Composition root
 *
 * Generated by Dependencies Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: cases
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Cases Domain Module - Composition root
 *
 * DDD: Composition root for cases domain. Exposes repos (ports) and use cases
 * grouped by aggregate. No orgId at build time — use execution context at call time.
 */

import {
  AssignRepositoryAdapter,
  CaseRepositoryAdapter,
  CloseRepositoryAdapter,
} from "@aegora/adapters/cases";
import { getIdGeneratorService } from "@aegora/adapters";
import type { AdapterDynamoDBClient } from "@aegora/adapters";
import { executionContextService } from "../../../lib/execution-context.service.js";
// Use-case constructors (concrete)
import {
  ExecuteAssignCase,
  ExecuteCloseCase,
  ExecuteGetCase,
  ExecuteListCases,
  ExecuteOpenCase,
} from "@aegora/services/cases/usecases";
// Ports (interfaces)
import type {
  AssignRepository,
  CaseRepository,
  CloseRepository,
} from "@aegora/services/cases/ports";

export interface CasesDomainModule {
  repos: {
    assigns: AssignRepository;
    cases: CaseRepository;
    closes: CloseRepository;
  };
  useCases: {
    assigns: {
      get: ExecuteAssignCase;
    };
    cases: {
      get: ExecuteGetCase;
      list: ExecuteListCases;
    };
    closes: {
      get: ExecuteCloseCase;
    };
  };
}

export function buildCasesDomainModule(
  dynamoClient: AdapterDynamoDBClient,
): CasesDomainModule {
  // Adapters implementing ports (adapters encapsulate Ddb)
  const repos = (() => {
    const obj: {
      assigns?: AssignRepository;
      cases?: CaseRepository;
      closes?: CloseRepository;
    } = {};

    obj.assigns = new AssignRepositoryAdapter(dynamoClient);
    obj.cases = new CaseRepositoryAdapter(dynamoClient);
    obj.closes = new CloseRepositoryAdapter(dynamoClient);
    return {
      assigns: obj.assigns!,
      cases: obj.cases!,
      closes: obj.closes!,
    };
  })();

  const executionContext = executionContextService;
  const idGenerator = getIdGeneratorService();

  // Use cases depend only on ports (repos.*)
  const useCases = {
    assigns: {
      get: new ExecuteAssignCase(executionContext, idGenerator, repos.assigns),
    },
    cases: {
      get: new ExecuteGetCase(executionContext, idGenerator, repos.cases),
      list: new ExecuteListCases(executionContext, idGenerator, repos.cases),
    },
    closes: {
      get: new ExecuteCloseCase(executionContext, idGenerator, repos.closes),
    },
  };
  return { repos, useCases: useCases as CasesDomainModule["useCases"] };
}
