/**
 * CloseRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: cases
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * CloseRepository Port
 *
 * DDD: Application port for closerepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { CloseCaseInput, CloseCaseOutput } from "../dto/close.dto";
export interface CloseRepository {
  closeCase(input: CloseCaseInput): Promise<CloseCaseOutput>;
}

export type { CloseCaseInput, CloseCaseOutput } from "../dto/close.dto";
