/**
 * GetEvent handler tests
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: events
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { describe, it, expect, beforeEach, vi } from "vitest";
import { getEvent } from "@aegora/api-server/domains/events/handlers";
import type { EventsDDDDependencies } from "@aegora/api-server/domains/events";
import { createEvent as createEventEntity } from "@aegora/factories/events";
import { createMockRequest, createMockReply, createMockDependencies, TEST_ORG_ID } from "@aegora/tests/shared";
import { EVENTS_USE_CASES } from "../__factories__/use-cases.js";

describe("GetEvent", () => {
  let mockRequest: ReturnType<typeof createMockRequest>;
  let mockReply: ReturnType<typeof createMockReply>;
  let mockDeps: EventsDDDDependencies;
  const orgId = TEST_ORG_ID;

  beforeEach(() => {
    mockRequest = createMockRequest({ orgId });
    mockReply = createMockReply();
    mockDeps = createMockDependencies<EventsDDDDependencies>(
      EVENTS_USE_CASES,
      {
        // Mock use case dependencies here
      }
    );
  });

  it("should return 200 with entity when found", async () => {
    const entity = createEventEntity({ orgId });
    const useCaseResult = { data: entity, meta: { correlationId: "test", timestamp: new Date().toISOString() } };
    
    vi.spyOn(mockDeps.executeGetEvent, "execute").mockResolvedValue(useCaseResult);
    mockRequest.params = { eventId: entity.id };

    await getEvent(mockRequest, mockReply, mockDeps);

    expect(mockDeps.executeGetEvent.execute).toHaveBeenCalledWith(expect.objectContaining({ eventId: entity.id }));
    expect(mockReply.code).toHaveBeenCalledWith(200);
    expect(mockReply.send).toHaveBeenCalledWith(useCaseResult);
  });

  it("should return error when entity not found", async () => {
    const nonExistentId = "non-existent-id";
    mockRequest.params = { eventId: nonExistentId };
    
    vi.spyOn(mockDeps.executeGetEvent, "execute").mockRejectedValue(
      new Error("Entity not found")
    );

    await expect(
      getEvent(mockRequest, mockReply, mockDeps)
    ).rejects.toThrow();
  });

});
