/**
 * ListEvents handler tests
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: events
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { describe, it, expect, beforeEach, vi } from "vitest";
import { listEvents } from "@aegora/api-server/domains/events/handlers";
import type { EventsDDDDependencies } from "@aegora/api-server/domains/events";
import { createEvent as createEventEntity } from "@aegora/factories/events";
import { createMockRequest, createMockReply, createMockDependencies, TEST_ORG_ID } from "@aegora/tests/shared";
import { EVENTS_USE_CASES } from "../__factories__/use-cases.js";

describe("ListEvents", () => {
  let mockRequest: ReturnType<typeof createMockRequest>;
  let mockReply: ReturnType<typeof createMockReply>;
  let mockDeps: EventsDDDDependencies;
  const orgId = TEST_ORG_ID;

  beforeEach(() => {
    mockRequest = createMockRequest({ orgId });
    mockReply = createMockReply();
    mockDeps = createMockDependencies<EventsDDDDependencies>(
      EVENTS_USE_CASES,
      {
        // Mock use case dependencies here
      }
    );
  });

  it("should return 200 with list of entities", async () => {
    const entities = [
      createEventEntity({ orgId }),
      createEventEntity({ orgId }),
    ];
    const useCaseResult = {
      data: { items: entities, nextCursor: undefined, prevCursor: undefined },
      meta: { correlationId: "test", timestamp: new Date().toISOString(), pagination: {} }
    };
    
    vi.spyOn(mockDeps.executeListEvents, "execute").mockResolvedValue(useCaseResult);

    await listEvents(mockRequest, mockReply, mockDeps);

    expect(mockDeps.executeListEvents.execute).toHaveBeenCalledWith(expect.anything());
    expect(mockReply.code).toHaveBeenCalledWith(200);
    expect(mockReply.send).toHaveBeenCalledWith(useCaseResult);
  });

});
