/**
 * Main Core Package Index
 *
 * Generated by Main Index Builder Generator v1.0.0
 * Generator Version: 2.0.0
 * Domain: events
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * @aegora/core - Main Barrel Export
 *
 * Central export point for all core business logic, entities, repositories, and types
 * Organized by domain for easy importing
 *
 * Usage:
 *   // Namespace imports (recommended for new code)
 *   import { activity, ai } from "@aegora/core";
 *   const { repositories, types } = activity;
 *
 *   // Direct domain imports (via package.json exports)
 *   import { ActivityRepository } from "@aegora/core/activity/repositories/index.js";
 *   import { ActivityEntity } from "@aegora/core/activity/models/index.js";
 *   import { ActivitySchemas } from "@aegora/core/activity/schemas/index.js";
 *
 *   // Flat schema imports
 *   import { ActivitySchemas, AiSchemas } from "@aegora/core";
 */

// ============================================================================
// DOMAIN EXPORTS (using namespace to avoid duplicate shared type conflicts)
// ============================================================================
// Export domains as namespaces to prevent TS2308 errors from duplicate exports
// of shared types (AccountId, OrgId, PageInfo, components, operations)
// NOTE: _shared is NOT a domain and is exported separately

import * as __shared from "./_shared/index.js";
import * as _alerts from "./alerts/index.js";
import * as _audits from "./audits/index.js";
import * as _cases from "./cases/index.js";
import * as _events from "./events/index.js";
import * as _holds from "./holds/index.js";
import * as _identity from "./identity/index.js";
import * as _models from "./models/index.js";
import * as _offers from "./offers/index.js";
import * as _policies from "./policies/index.js";

// Export as namespaces
export const _shared = __shared;
export const alerts = _alerts;
export const audits = _audits;
export const cases = _cases;
export const events = _events;
export const holds = _holds;
export const identity = _identity;
export const models = _models;
export const offers = _offers;
export const policies = _policies;

// ============================================================================
// FLAT EXPORTS (for direct imports)
// ============================================================================
// Export schemas from each domain for convenience
// NOTE: Types, repositories, models, and value-objects are available via:
//   - Namespace exports: import { activity } from "@aegora/core"; activity.types.*
//   - Direct exports: import * from "@aegora/core/activity/types/index.js"
//   - Direct exports: import * from "@aegora/core/activity/repositories/index.js"
//   - Direct exports: import * from "@aegora/core/activity/models/index.js"
//   - Direct exports: import * from "@aegora/core/activity/value-objects/index.js"

// Shared utilities and helpers
// These exports are required by platform/api-server and platform/services
export {
  DOMAIN_PREFIX_MAP,
  isValidDomainId,
  extractDomainFromId,
} from "./_shared/index.js";
export type { DomainCode, DomainPrefix } from "./_shared/index.js";

// Alerts Service
export { schemas as AlertsSchemas } from "./alerts/schemas/alerts.schemas.js";

// Audits Service
export { schemas as AuditsSchemas } from "./audits/schemas/audits.schemas.js";

// Cases Service
export { schemas as CasesSchemas } from "./cases/schemas/cases.schemas.js";

// Events Service
export { schemas as EventsSchemas } from "./events/schemas/events.schemas.js";

// Holds Service
export { schemas as HoldsSchemas } from "./holds/schemas/holds.schemas.js";

// Identity Service
export { schemas as IdentitySchemas } from "./identity/schemas/identity.schemas.js";

// Models Service
export { schemas as ModelsSchemas } from "./models/schemas/models.schemas.js";

// Offers Service
export { schemas as OffersSchemas } from "./offers/schemas/offers.schemas.js";

// Policies Service
export { schemas as PoliciesSchemas } from "./policies/schemas/policies.schemas.js";

