/**
 * Holds DDD Dependencies - Composition root
 *
 * Generated by Dependencies Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: holds
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Holds Domain Module - Composition root
 *
 * DDD: Composition root for holds domain. Exposes repos (ports) and use cases
 * grouped by aggregate. No orgId at build time — use execution context at call time.
 */

import {
  ConfirmRepositoryAdapter,
  DisputeRepositoryAdapter,
  HoldRepositoryAdapter,
  ReleaseRepositoryAdapter,
  ResolveRepositoryAdapter,
} from "@aegora/adapters/holds";
import { getIdGeneratorService } from "@aegora/adapters";
import type { AdapterDynamoDBClient } from "@aegora/adapters";
import { executionContextService } from "../../../lib/execution-context.service.js";
// Use-case constructors (concrete)
import {
  ExecuteConfirmHold,
  ExecuteCreateHold,
  ExecuteCreateHoldDispute,
  ExecuteGetHold,
  ExecuteListHoldDisputes,
  ExecuteListHolds,
  ExecuteReleaseHold,
  ExecuteResolveDispute,
} from "@aegora/services/holds/usecases";
// Ports (interfaces)
import type {
  ConfirmRepository,
  DisputeRepository,
  HoldRepository,
  ReleaseRepository,
  ResolveRepository,
} from "@aegora/services/holds/ports";

export interface HoldsDomainModule {
  repos: {
    confirms: ConfirmRepository;
    disputes: DisputeRepository;
    holds: HoldRepository;
    releases: ReleaseRepository;
    resolves: ResolveRepository;
  };
  useCases: {
    confirms: {
      get: ExecuteConfirmHold;
    };
    disputes: {
      create: ExecuteCreateHoldDispute;
      list: ExecuteListHoldDisputes;
    };
    holds: {
      create: ExecuteCreateHold;
      get: ExecuteGetHold;
      list: ExecuteListHolds;
    };
    releases: {
      get: ExecuteReleaseHold;
    };
    resolves: {
      get: ExecuteResolveDispute;
    };
  };
}

export function buildHoldsDomainModule(
  dynamoClient: AdapterDynamoDBClient,
): HoldsDomainModule {
  // Adapters implementing ports (adapters encapsulate Ddb)
  const repos = (() => {
    const obj: {
      confirms?: ConfirmRepository;
      disputes?: DisputeRepository;
      holds?: HoldRepository;
      releases?: ReleaseRepository;
      resolves?: ResolveRepository;
    } = {};

    obj.confirms = new ConfirmRepositoryAdapter(dynamoClient);
    obj.disputes = new DisputeRepositoryAdapter(dynamoClient);
    obj.holds = new HoldRepositoryAdapter(dynamoClient);
    obj.releases = new ReleaseRepositoryAdapter(dynamoClient);
    obj.resolves = new ResolveRepositoryAdapter(dynamoClient);
    return {
      confirms: obj.confirms!,
      disputes: obj.disputes!,
      holds: obj.holds!,
      releases: obj.releases!,
      resolves: obj.resolves!,
    };
  })();

  const executionContext = executionContextService;
  const idGenerator = getIdGeneratorService();

  // Use cases depend only on ports (repos.*)
  const useCases = {
    confirms: {
      get: new ExecuteConfirmHold(executionContext, idGenerator, repos.confirms),
    },
    disputes: {
      create: new ExecuteCreateHoldDispute(executionContext, idGenerator, repos.disputes),
      list: new ExecuteListHoldDisputes(executionContext, idGenerator, repos.disputes),
    },
    holds: {
      create: new ExecuteCreateHold(executionContext, idGenerator, repos.holds),
      get: new ExecuteGetHold(executionContext, idGenerator, repos.holds),
      list: new ExecuteListHolds(executionContext, idGenerator, repos.holds),
    },
    releases: {
      get: new ExecuteReleaseHold(executionContext, idGenerator, repos.releases),
    },
    resolves: {
      get: new ExecuteResolveDispute(executionContext, idGenerator, repos.resolves),
    },
  };
  return { repos, useCases: useCases as HoldsDomainModule["useCases"] };
}
