/**
 * Routes for Dispute
 *
 * Generated by Routes Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: holds
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyInstance, FastifyRequest, FastifyReply } from "fastify";
import { getDependencyContainer } from "../../../infrastructure/dependency-container.js";
import { createHoldDispute, listHoldDisputes } from "../handlers/dispute.handlers.js";
import { wrapHandlerInExecutionContext } from "../../../lib/execution-context-wrapper.js";

// Fastify types are available globally
export async function disputeRoutes(fastify: FastifyInstance) {
  // POST /v1/holds/{holdId}/disputes (unscoped; scope set for security middleware)
  fastify.post(
    "/v1/holds/:holdId/disputes",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: { holdId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getHoldsDependenciesForRequest();
        await createHoldDispute(request, reply, deps);
      });
    }
  );


  // GET /v1/holds/{holdId}/disputes (unscoped; scope set for security middleware)
  fastify.get(
    "/v1/holds/:holdId/disputes",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: { holdId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getHoldsDependenciesForRequest();
        await listHoldDisputes(request, reply, deps);
      });
    }
  );


}
