/**
 * Routes index
 *
 * Generated by Routes Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: holds
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

export { confirmRoutes } from "./confirm.routes.js";
export { disputeRoutes } from "./dispute.routes.js";
export { holdRoutes } from "./hold.routes.js";
export { releaseRoutes } from "./release.routes.js";
export { resolveRoutes } from "./resolve.routes.js";
