/**
 * Routes for Resolve
 *
 * Generated by Routes Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: holds
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyInstance, FastifyRequest, FastifyReply } from "fastify";
import { getDependencyContainer } from "../../../infrastructure/dependency-container.js";
import { resolveDispute } from "../handlers/resolve.handlers.js";
import { wrapHandlerInExecutionContext } from "../../../lib/execution-context-wrapper.js";

// Fastify types are available globally
export async function resolveRoutes(fastify: FastifyInstance) {
  // POST /v1/disputes/{disputeId}/resolve (unscoped; scope set for security middleware)
  fastify.post(
    "/v1/disputes/:disputeId/resolve",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: { disputeId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getHoldsDependenciesForRequest();
        await resolveDispute(request, reply, deps);
      });
    }
  );


}
