/**
 * ListHoldDisputes handler tests
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: holds
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { describe, it, expect, beforeEach, vi } from "vitest";
import { listHoldDisputes } from "@aegora/api-server/domains/holds/handlers";
import type { HoldsDDDDependencies } from "@aegora/api-server/domains/holds";
import { createDispute as createDisputeEntity } from "@aegora/factories/holds";
import { createMockRequest, createMockReply, createMockDependencies, TEST_ORG_ID } from "@aegora/tests/shared";
import { HOLDS_USE_CASES } from "../__factories__/use-cases.js";

describe("ListHoldDisputes", () => {
  let mockRequest: ReturnType<typeof createMockRequest>;
  let mockReply: ReturnType<typeof createMockReply>;
  let mockDeps: HoldsDDDDependencies;
  const orgId = TEST_ORG_ID;

  beforeEach(() => {
    mockRequest = createMockRequest({ orgId });
    mockReply = createMockReply();
    mockDeps = createMockDependencies<HoldsDDDDependencies>(
      HOLDS_USE_CASES,
      {
        // Mock use case dependencies here
      }
    );
  });

  it("should return 200 with list of entities", async () => {
    const entities = [
      createDisputeEntity({ orgId }),
      createDisputeEntity({ orgId }),
    ];
    const useCaseResult = {
      data: { items: entities, nextCursor: undefined, prevCursor: undefined },
      meta: { correlationId: "test", timestamp: new Date().toISOString(), pagination: {} }
    };
    
    vi.spyOn(mockDeps.executeListHoldDisputes, "execute").mockResolvedValue(useCaseResult);

    await listHoldDisputes(mockRequest, mockReply, mockDeps);

    expect(mockDeps.executeListHoldDisputes.execute).toHaveBeenCalledWith(expect.anything());
    expect(mockReply.code).toHaveBeenCalledWith(200);
    expect(mockReply.send).toHaveBeenCalledWith(useCaseResult);
  });

});
