/**
 * DisableRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: policies
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * DisableRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements DisableRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  DisableRepository,
} from "@aegora/services/policies";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { DisableRepositoryDdb } from "./disable-repository.ddb.js";
import { PolicyRepositoryDdb } from "./policy-repository.ddb.js";

/**
 * DisableRepositoryAdapter
 *
 * Implements DisableRepository port for infrastructure layer.
 */
export class DisableRepositoryAdapter implements DisableRepository {
  private readonly ddb: DisableRepositoryDdb;
  private readonly policyDdb: PolicyRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new DisableRepositoryDdb(this.dynamoClient);
    this.policyDdb = new PolicyRepositoryDdb(this.dynamoClient);
  }

  async disablePolicy(input: Parameters<DisableRepository['disablePolicy']>[0]): Promise<Awaited<ReturnType<DisableRepository['disablePolicy']>>> {
    return await this.ddb.disablePolicy(input);
  }

  async getPolicy(input: { policyId: string; orgId?: string; correlationId?: string }): Promise<unknown> {
    return await this.policyDdb.getPolicy(input as any);
  }
}
