/**
 * Audits DDD Dependencies - Composition root
 *
 * Generated by Dependencies Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: audits
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Audits Domain Module - Composition root
 *
 * DDD: Composition root for audits domain. Exposes repos (ports) and use cases
 * grouped by aggregate. No orgId at build time — use execution context at call time.
 */

import {
  ExportRepositoryAdapter,
} from "@aegora/adapters/audits";
import { getIdGeneratorService } from "@aegora/adapters";
import type { AdapterDynamoDBClient } from "@aegora/adapters";
import { executionContextService } from "../../../lib/execution-context.service.js";
// Use-case constructors (concrete)
import {
  ExecuteCreateAuditExport,
  ExecuteGetAuditExport,
  ExecuteListAuditExports,
} from "@aegora/services/audits/usecases";
// Ports (interfaces)
import type {
  ExportRepository,
} from "@aegora/services/audits/ports";

export interface AuditsDomainModule {
  repos: {
    exports: ExportRepository;
  };
  useCases: {
    exports: {
      create: ExecuteCreateAuditExport;
      get: ExecuteGetAuditExport;
      list: ExecuteListAuditExports;
    };
  };
}

export function buildAuditsDomainModule(
  dynamoClient: AdapterDynamoDBClient,
): AuditsDomainModule {
  // Adapters implementing ports (adapters encapsulate Ddb)
  const repos = (() => {
    const obj: {
      exports?: ExportRepository;
    } = {};

    obj.exports = new ExportRepositoryAdapter(dynamoClient);
    return {
      exports: obj.exports!,
    };
  })();

  const executionContext = executionContextService;
  const idGenerator = getIdGeneratorService();

  // Use cases depend only on ports (repos.*)
  const useCases = {
    exports: {
      create: new ExecuteCreateAuditExport(executionContext, idGenerator, repos.exports),
      get: new ExecuteGetAuditExport(executionContext, idGenerator, repos.exports),
      list: new ExecuteListAuditExports(executionContext, idGenerator, repos.exports),
    },
  };
  return { repos, useCases: useCases as AuditsDomainModule["useCases"] };
}
