/**
 * Event DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: events
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Event DTOs
 *
 * DDD: Application DTOs for Event use cases.
 */

import type { GetEventParams, IngestEventRequestInput, ListEventsParams } from "@aegora/core/events/types";

export type ListEventsInput = ListEventsParams;

export type IngestEventInput = IngestEventRequestInput;

export type GetEventInput = GetEventParams;

export type ListEventsOutput = {};

export type IngestEventOutput = {};

export type GetEventOutput = {};
