/**
 * ExecuteRollbackModel - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: models
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteRollbackModel Use Case
 *
 * DDD: Application use case for get Rollback.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { RollbackModelInput, RollbackModelOutput } from "../dto/rollback.dto";
import type { ExecutionContextService, IdGeneratorService } from "@aegora/services/_shared/index.js";
import type { RollbackRepository } from "../ports";
import { NotFoundError, ValidationError } from "../errors";

export class ExecuteRollbackModel {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly rollback: RollbackRepository
  ) {}

  async execute(input: RollbackModelInput): Promise<RollbackModelOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.modelsId();

    // All field names extracted from OpenAPI spec: none
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!(input as any).modelId) {
      throw new ValidationError("modelId is required");
    }
    const modelId = (input as any).modelId;

    // Load entity via repository (pass correlation ID for response meta)
    const entity = await this.rollback.rollbackModel({ modelId: modelId, orgId: this.context.getOrgId(), correlationId } as any);
    if (!entity) {
      throw new NotFoundError(`Entity not found: ${modelId}`);
    }

    return entity as RollbackModelOutput;
  }
}
