/**
 * Repository interface for Dispute
 *
 * Generated by Repository Generator v1.0.0
 * Generator Version: 2.0.0
 * Domain: holds
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type {
  CreateReadRepository,
} from "../../_shared/repositories/_base-repository.js";

import type {
  DisputeEntity
} from "../models/dispute.entity.js";
import type {
  Dispute
} from "../types/index.js";
/**
 * DisputeRepository Interface
 */
export interface DisputeRepository extends CreateReadRepository<DisputeEntity, Dispute, string, Record<string, never>> {

}
