/**
 * DisputeRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: holds
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * DisputeRepository Port
 *
 * DDD: Application port for disputerepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { CreateHoldDisputeInput, CreateHoldDisputeOutput, ListHoldDisputesInput, ListHoldDisputesOutput } from "../dto/dispute.dto";
export interface DisputeRepository {
  listHoldDisputes(input: ListHoldDisputesInput): Promise<ListHoldDisputesOutput>;
  createHoldDispute(input: CreateHoldDisputeInput): Promise<CreateHoldDisputeOutput>;
}

export type { CreateHoldDisputeInput, CreateHoldDisputeOutput, ListHoldDisputesInput, ListHoldDisputesOutput } from "../dto/dispute.dto";
