/**
 * ReleaseRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: holds
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ReleaseRepository Port
 *
 * DDD: Application port for releaserepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { ReleaseHoldInput, ReleaseHoldOutput } from "../dto/release.dto";
export interface ReleaseRepository {
  releaseHold(input: ReleaseHoldInput): Promise<ReleaseHoldOutput>;
}

export type { ReleaseHoldInput, ReleaseHoldOutput } from "../dto/release.dto";
