/**
 * AlertRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: alerts
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * AlertRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements AlertRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  AlertRepository,
} from "@aegora/services/alerts";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { AlertRepositoryDdb } from "./alert-repository.ddb.js";

/**
 * AlertRepositoryAdapter
 *
 * Implements AlertRepository port for infrastructure layer.
 */
export class AlertRepositoryAdapter implements AlertRepository {
  private readonly ddb: AlertRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new AlertRepositoryDdb(this.dynamoClient);
  }

  async listAlerts(input: Parameters<AlertRepository['listAlerts']>[0]): Promise<Awaited<ReturnType<AlertRepository['listAlerts']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.listAlerts(input);
  }

  async createAlert(input: Parameters<AlertRepository['createAlert']>[0]): Promise<Awaited<ReturnType<AlertRepository['createAlert']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.createAlert(input);
  }

  async getAlert(input: Parameters<AlertRepository['getAlert']>[0]): Promise<Awaited<ReturnType<AlertRepository['getAlert']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.getAlert(input);
  }
}
