/**
 * SuppressRepository - DynamoDB Implementation
 *
 * Generated by DynamoDB Repository Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: alerts
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * SuppressRepositoryDdb
 *
 * DDD: Infrastructure adapter for Suppress repository.
 * ⚠️  Missing x-dynamodb metadata - implementation not generated.
 */

import type { SuppressRepository } from "@aegora/services/alerts";

export class SuppressRepositoryDdb implements SuppressRepository {
  constructor(private readonly dynamoClient: any) {}

  async suppressAlert(input: Parameters<SuppressRepository['suppressAlert']>[0]): Promise<Awaited<ReturnType<SuppressRepository['suppressAlert']>>> {
    // TODO: Implement using x-dynamodb metadata
    throw new Error("Not implemented - missing x-dynamodb metadata");
  }
}
