/**
 * ListEvent DTO Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: events
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import type { ListEventsParams } from "@aegora/core/events";

export function createListEventRequest(overrides: Partial<ListEventsParams> = {}) {
  const raw = {
    ...overrides,
  };

  return raw;
}
