/**
 * ConsentRecord Entity - Domain model
 *
 * Generated by Entity Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: offers
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { components } from "../openapi/offers.openapi.types.js";
import { schemas } from "../schemas/offers.schemas.js";

/**
 * Entity: ConsentRecordEntity
 * Description: Represents the ConsentRecord domain model.
 * Source: schemas.ConsentRecord
 * Type: Domain Entity (API)
 */
export const ConsentRecordEntitySchema = schemas.ConsentRecord;
export type ConsentRecordEntity = components["schemas"]["ConsentRecord"];
