/**
 * Models barrel export - All Offers entities
 *
 * Generated by Entity Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: offers
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

export * from "./consent-record.entity.js";
export * from "./offer.entity.js";
export * from "./override.entity.js";
