/**
 * Offer Entity - Domain model
 *
 * Generated by Entity Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: offers
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { components } from "../openapi/offers.openapi.types.js";
import { schemas } from "../schemas/offers.schemas.js";

/**
 * Entity: OfferEntity
 * Description: Represents the Offer domain model.
 * Source: schemas.Offer
 * Type: Domain Entity (API)
 */
export const OfferEntitySchema = schemas.Offer;
export type OfferEntity = components["schemas"]["Offer"];
