/**
 * Override Entity - Domain model
 *
 * Generated by Entity Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: offers
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { components } from "../openapi/offers.openapi.types.js";
import { schemas } from "../schemas/offers.schemas.js";

/**
 * Entity: OverrideEntity
 * Description: Represents the Override domain model.
 * Source: schemas.Override
 * Type: Domain Entity (API)
 */
export const OverrideEntitySchema = schemas.Override;
export type OverrideEntity = components["schemas"]["Override"];
