/**
 * ListConsentRecord DTO Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: offers
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import type { ListConsentRecordsParams } from "@aegora/core/offers";

export function createListConsentRecordRequest(overrides: Partial<ListConsentRecordsParams> = {}) {
  const raw = {
    ...overrides,
  };

  return raw;
}
