/**
 * CaseRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: cases
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * CaseRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements CaseRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  CaseRepository,
} from "@aegora/services/cases";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { CaseRepositoryDdb } from "./case-repository.ddb.js";

/**
 * CaseRepositoryAdapter
 *
 * Implements CaseRepository port for infrastructure layer.
 */
export class CaseRepositoryAdapter implements CaseRepository {
  private readonly ddb: CaseRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new CaseRepositoryDdb(this.dynamoClient);
  }

  async listCases(input: Parameters<CaseRepository['listCases']>[0]): Promise<Awaited<ReturnType<CaseRepository['listCases']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.listCases(input);
  }

  async openCase(input: Parameters<CaseRepository['openCase']>[0]): Promise<Awaited<ReturnType<CaseRepository['openCase']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.openCase(input);
  }

  async getCase(input: Parameters<CaseRepository['getCase']>[0]): Promise<Awaited<ReturnType<CaseRepository['getCase']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.getCase(input);
  }
}
