/**
 * Offers DDD Dependencies - Composition root
 *
 * Generated by Dependencies Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: offers
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Offers Domain Module - Composition root
 *
 * DDD: Composition root for offers domain. Exposes repos (ports) and use cases
 * grouped by aggregate. No orgId at build time — use execution context at call time.
 */

import {
  BlockRepositoryAdapter,
  ConsentRecordRepositoryAdapter,
  DeliverRepositoryAdapter,
  OfferRepositoryAdapter,
  OverrideRepositoryAdapter,
} from "@aegora/adapters/offers";
import { getIdGeneratorService } from "@aegora/adapters";
import type { AdapterDynamoDBClient } from "@aegora/adapters";
import { executionContextService } from "../../../lib/execution-context.service.js";
// Use-case constructors (concrete)
import {
  ExecuteBlockOffer,
  ExecuteCreateConsentRecord,
  ExecuteCreateOffer,
  ExecuteDeliverOffer,
  ExecuteGetOffer,
  ExecuteListConsentRecords,
  ExecuteListOfferOverrides,
  ExecuteListOffers,
  ExecuteOverrideOffer,
} from "@aegora/services/offers/usecases";
// Ports (interfaces)
import type {
  BlockRepository,
  ConsentRecordRepository,
  DeliverRepository,
  OfferRepository,
  OverrideRepository,
} from "@aegora/services/offers/ports";

export interface OffersDomainModule {
  repos: {
    blocks: BlockRepository;
    consentRecords: ConsentRecordRepository;
    delivers: DeliverRepository;
    offers: OfferRepository;
    overrides: OverrideRepository;
  };
  useCases: {
    blocks: {
      get: ExecuteBlockOffer;
    };
    consentRecords: {
      create: ExecuteCreateConsentRecord;
      list: ExecuteListConsentRecords;
    };
    delivers: {
      get: ExecuteDeliverOffer;
    };
    offers: {
      create: ExecuteCreateOffer;
      get: ExecuteGetOffer;
      list: ExecuteListOffers;
    };
    overrides: {
      get: ExecuteOverrideOffer;
      list: ExecuteListOfferOverrides;
    };
  };
}

export function buildOffersDomainModule(
  dynamoClient: AdapterDynamoDBClient,
): OffersDomainModule {
  // Adapters implementing ports (adapters encapsulate Ddb)
  const repos = (() => {
    const obj: {
      blocks?: BlockRepository;
      consentRecords?: ConsentRecordRepository;
      delivers?: DeliverRepository;
      offers?: OfferRepository;
      overrides?: OverrideRepository;
    } = {};

    obj.blocks = new BlockRepositoryAdapter(dynamoClient);
    obj.consentRecords = new ConsentRecordRepositoryAdapter(dynamoClient);
    obj.delivers = new DeliverRepositoryAdapter(dynamoClient);
    obj.offers = new OfferRepositoryAdapter(dynamoClient);
    obj.overrides = new OverrideRepositoryAdapter(dynamoClient);
    return {
      blocks: obj.blocks!,
      consentRecords: obj.consentRecords!,
      delivers: obj.delivers!,
      offers: obj.offers!,
      overrides: obj.overrides!,
    };
  })();

  const executionContext = executionContextService;
  const idGenerator = getIdGeneratorService();

  // Use cases depend only on ports (repos.*)
  const useCases = {
    blocks: {
      get: new ExecuteBlockOffer(executionContext, idGenerator, repos.blocks),
    },
    consentRecords: {
      create: new ExecuteCreateConsentRecord(executionContext, idGenerator, repos.consentRecords),
      list: new ExecuteListConsentRecords(executionContext, idGenerator, repos.consentRecords),
    },
    delivers: {
      get: new ExecuteDeliverOffer(executionContext, idGenerator, repos.delivers),
    },
    offers: {
      create: new ExecuteCreateOffer(executionContext, idGenerator, repos.offers),
      get: new ExecuteGetOffer(executionContext, idGenerator, repos.offers),
      list: new ExecuteListOffers(executionContext, idGenerator, repos.offers),
    },
    overrides: {
      get: new ExecuteOverrideOffer(executionContext, idGenerator, repos.overrides),
      list: new ExecuteListOfferOverrides(executionContext, idGenerator, repos.overrides),
    },
  };
  return { repos, useCases: useCases as OffersDomainModule["useCases"] };
}
