/**
 * PromoteRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: models
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * PromoteRepository Port
 *
 * DDD: Application port for promoterepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { PromoteModelInput, PromoteModelOutput } from "../dto/promote.dto";
export interface PromoteRepository {
  promoteModel(input: PromoteModelInput): Promise<PromoteModelOutput>;
}

export type { PromoteModelInput, PromoteModelOutput } from "../dto/promote.dto";
