/**
 * ExecuteCreatePolicy - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: policies
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteCreatePolicy Use Case
 *
 * DDD: Application use case for create Policy.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { CreatePolicyInput, CreatePolicyOutput } from "../dto/policy.dto";
import type { ExecutionContextService, IdGeneratorService } from "@aegora/services/_shared/index.js";
import type { PolicyRepository } from "../ports";
import { PermissionDeniedError, ValidationError } from "../errors";
import { CanCreate } from "../policies/can-create.policy";
export class ExecuteCreatePolicy {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly policy: PolicyRepository
  ) {}

  async execute(input: CreatePolicyInput): Promise<CreatePolicyOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.policiesId();

    // All field names extracted from OpenAPI spec: effect, enabled, feeIncentiveNote, fromPurpose, name, toPurpose
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!input.fromPurpose) {
      throw new ValidationError("fromPurpose is required");
    }
    if (!input.toPurpose) {
      throw new ValidationError("toPurpose is required");
    }
    if (!input.effect) {
      throw new ValidationError("effect is required");
    }
    if (!input.name) {
      throw new ValidationError("name is required");
    }    // Check policy
    if (!CanCreate.allow({} as any, "")) {
      throw new PermissionDeniedError("Operation not allowed");
    }

    // Generate entity ID in services layer using IdGeneratorService (policies domain)
    const entityId = this.idGenerator.policiesId();

    // Create entity via repository (pass ID and correlation ID for response meta)
    const entity = await this.policy.createPolicy({ ...input, id: entityId, createdByActorId: (input as any).createdByActorId ?? this.context.getUserId(), createdByActorType: (input as any).createdByActorType ?? "human", orgId: this.context.getOrgId(), correlationId } as any);

    return entity as CreatePolicyOutput;
  }
}
