/**
 * Confirm DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: holds
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Confirm DTOs
 *
 * DDD: Application DTOs for Confirm use cases.
 */

import type { ConfirmHoldParams } from "@aegora/core/holds/types";

export type ConfirmHoldInput = ConfirmHoldParams;

export type ConfirmHoldOutput = {};
