/**
 * Dispute DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: holds
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Dispute DTOs
 *
 * DDD: Application DTOs for Dispute use cases.
 */

import type { CreateHoldDisputeParams, CreateHoldDisputeRequestInput, ListHoldDisputesParams } from "@aegora/core/holds/types";

export type ListHoldDisputesInput = ListHoldDisputesParams;

export type CreateHoldDisputeInput = CreateHoldDisputeParams & CreateHoldDisputeRequestInput;

export type ListHoldDisputesOutput = {};

export type CreateHoldDisputeOutput = {};
