/**
 * Release DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: holds
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Release DTOs
 *
 * DDD: Application DTOs for Release use cases.
 */

import type { ReleaseHoldParams, ReleaseHoldRequestInput } from "@aegora/core/holds/types";

export type ReleaseHoldInput = ReleaseHoldParams & ReleaseHoldRequestInput;

export type ReleaseHoldOutput = {};
