/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v1/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List purpose-tagged events */
        get: operations["listEvents"];
        put?: never;
        /** Ingest a purpose-tagged event */
        post: operations["ingestEvent"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/events/{eventId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get an event */
        get: operations["getEvent"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description Bank customer identifier (opaque to Aegora). */
        CustomerId: string;
        /**
         * @description Declared processing purpose (help vs protect). Required before an action may fire.
         * @enum {string}
         */
        Purpose: "help" | "protect";
        /** @description RFC 7807 Problem Details (provisional mapping for gateway errors). */
        Problem: {
            /**
             * Format: uri
             * @description URI reference identifying the problem type.
             */
            type?: string;
            /** @description Short human-readable summary. */
            title?: string;
            /** @description HTTP status code. */
            status?: number;
            /** @description Human-readable explanation specific to this occurrence. */
            detail?: string;
            /**
             * Format: uri
             * @description URI reference identifying this occurrence.
             */
            instance?: string;
            /** @description Optional machine-readable error code from the gateway. */
            code?: string;
        } & {
            [key: string]: unknown;
        };
        EventId: string;
        Event: {
            eventId: string;
            /** @description Bank customer identifier (opaque to Aegora). */
            customerId: string;
            /**
             * @description Declared processing purpose (help vs protect). Required before an action may fire.
             * @enum {string}
             */
            purpose: "help" | "protect";
            /** @enum {string} */
            eventType: "cardAuthorisation" | "appSession" | "transaction" | "networkFlow" | "consentChange";
            /** Format: date-time */
            occurredAt: string;
            /** @description Channel-safe payload. Network packet dumps are not stored here. */
            payload?: {
                [key: string]: unknown;
            };
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt?: string;
        };
        EventListData: {
            items: {
                eventId: string;
                /** @description Bank customer identifier (opaque to Aegora). */
                customerId: string;
                /**
                 * @description Declared processing purpose (help vs protect). Required before an action may fire.
                 * @enum {string}
                 */
                purpose: "help" | "protect";
                /** @enum {string} */
                eventType: "cardAuthorisation" | "appSession" | "transaction" | "networkFlow" | "consentChange";
                /** Format: date-time */
                occurredAt: string;
                /** @description Channel-safe payload. Network packet dumps are not stored here. */
                payload?: {
                    [key: string]: unknown;
                };
                /** Format: date-time */
                createdAt: string;
                /** Format: date-time */
                updatedAt?: string;
            }[];
        };
        ResponseMeta: {
            /**
             * Format: uuid
             * @description Correlation id for this HTTP request.
             */
            requestId?: string;
            /** @description Optional end-to-end correlation id. */
            correlationId?: string;
            /**
             * Format: date-time
             * @description Server time when the payload was produced.
             */
            generatedAt?: string;
        };
        EventListResponse: {
            data: {
                items: {
                    eventId: string;
                    /** @description Bank customer identifier (opaque to Aegora). */
                    customerId: string;
                    /**
                     * @description Declared processing purpose (help vs protect). Required before an action may fire.
                     * @enum {string}
                     */
                    purpose: "help" | "protect";
                    /** @enum {string} */
                    eventType: "cardAuthorisation" | "appSession" | "transaction" | "networkFlow" | "consentChange";
                    /** Format: date-time */
                    occurredAt: string;
                    /** @description Channel-safe payload. Network packet dumps are not stored here. */
                    payload?: {
                        [key: string]: unknown;
                    };
                    /** Format: date-time */
                    createdAt: string;
                    /** Format: date-time */
                    updatedAt?: string;
                }[];
            };
            meta?: {
                /**
                 * Format: uuid
                 * @description Correlation id for this HTTP request.
                 */
                requestId?: string;
                /** @description Optional end-to-end correlation id. */
                correlationId?: string;
                /**
                 * Format: date-time
                 * @description Server time when the payload was produced.
                 */
                generatedAt?: string;
            };
        };
        EventIngest: {
            /** @description Bank customer identifier (opaque to Aegora). */
            customerId: string;
            /**
             * @description Declared processing purpose (help vs protect). Required before an action may fire.
             * @enum {string}
             */
            purpose: "help" | "protect";
            /** @enum {string} */
            eventType: "cardAuthorisation" | "appSession" | "transaction" | "networkFlow" | "consentChange";
            /** Format: date-time */
            occurredAt: string;
            payload?: {
                [key: string]: unknown;
            };
        };
        EventResponse: {
            data: {
                eventId: string;
                /** @description Bank customer identifier (opaque to Aegora). */
                customerId: string;
                /**
                 * @description Declared processing purpose (help vs protect). Required before an action may fire.
                 * @enum {string}
                 */
                purpose: "help" | "protect";
                /** @enum {string} */
                eventType: "cardAuthorisation" | "appSession" | "transaction" | "networkFlow" | "consentChange";
                /** Format: date-time */
                occurredAt: string;
                /** @description Channel-safe payload. Network packet dumps are not stored here. */
                payload?: {
                    [key: string]: unknown;
                };
                /** Format: date-time */
                createdAt: string;
                /** Format: date-time */
                updatedAt?: string;
            };
            meta?: {
                /**
                 * Format: uuid
                 * @description Correlation id for this HTTP request.
                 */
                requestId?: string;
                /** @description Optional end-to-end correlation id. */
                correlationId?: string;
                /**
                 * Format: date-time
                 * @description Server time when the payload was produced.
                 */
                generatedAt?: string;
            };
        };
    };
    responses: {
        /** @description Error (RFC 7807 Problem Details) */
        Problem: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": {
                    /**
                     * Format: uri
                     * @description URI reference identifying the problem type.
                     */
                    type?: string;
                    /** @description Short human-readable summary. */
                    title?: string;
                    /** @description HTTP status code. */
                    status?: number;
                    /** @description Human-readable explanation specific to this occurrence. */
                    detail?: string;
                    /**
                     * Format: uri
                     * @description URI reference identifying this occurrence.
                     */
                    instance?: string;
                    /** @description Optional machine-readable error code from the gateway. */
                    code?: string;
                } & {
                    [key: string]: unknown;
                };
                "application/json": {
                    /**
                     * Format: uri
                     * @description URI reference identifying the problem type.
                     */
                    type?: string;
                    /** @description Short human-readable summary. */
                    title?: string;
                    /** @description HTTP status code. */
                    status?: number;
                    /** @description Human-readable explanation specific to this occurrence. */
                    detail?: string;
                    /**
                     * Format: uri
                     * @description URI reference identifying this occurrence.
                     */
                    instance?: string;
                    /** @description Optional machine-readable error code from the gateway. */
                    code?: string;
                } & {
                    [key: string]: unknown;
                };
            };
        };
        /** @description Missing or invalid API key */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": {
                    /**
                     * Format: uri
                     * @description URI reference identifying the problem type.
                     */
                    type?: string;
                    /** @description Short human-readable summary. */
                    title?: string;
                    /** @description HTTP status code. */
                    status?: number;
                    /** @description Human-readable explanation specific to this occurrence. */
                    detail?: string;
                    /**
                     * Format: uri
                     * @description URI reference identifying this occurrence.
                     */
                    instance?: string;
                    /** @description Optional machine-readable error code from the gateway. */
                    code?: string;
                } & {
                    [key: string]: unknown;
                };
                "application/json": {
                    /**
                     * Format: uri
                     * @description URI reference identifying the problem type.
                     */
                    type?: string;
                    /** @description Short human-readable summary. */
                    title?: string;
                    /** @description HTTP status code. */
                    status?: number;
                    /** @description Human-readable explanation specific to this occurrence. */
                    detail?: string;
                    /**
                     * Format: uri
                     * @description URI reference identifying this occurrence.
                     */
                    instance?: string;
                    /** @description Optional machine-readable error code from the gateway. */
                    code?: string;
                } & {
                    [key: string]: unknown;
                };
            };
        };
        /** @description Semantically invalid request (e.g. PACK_EMPTY) */
        UnprocessableEntity: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": {
                    /**
                     * Format: uri
                     * @description URI reference identifying the problem type.
                     */
                    type?: string;
                    /** @description Short human-readable summary. */
                    title?: string;
                    /** @description HTTP status code. */
                    status?: number;
                    /** @description Human-readable explanation specific to this occurrence. */
                    detail?: string;
                    /**
                     * Format: uri
                     * @description URI reference identifying this occurrence.
                     */
                    instance?: string;
                    /** @description Optional machine-readable error code from the gateway. */
                    code?: string;
                } & {
                    [key: string]: unknown;
                };
                "application/json": {
                    /**
                     * Format: uri
                     * @description URI reference identifying the problem type.
                     */
                    type?: string;
                    /** @description Short human-readable summary. */
                    title?: string;
                    /** @description HTTP status code. */
                    status?: number;
                    /** @description Human-readable explanation specific to this occurrence. */
                    detail?: string;
                    /**
                     * Format: uri
                     * @description URI reference identifying this occurrence.
                     */
                    instance?: string;
                    /** @description Optional machine-readable error code from the gateway. */
                    code?: string;
                } & {
                    [key: string]: unknown;
                };
            };
        };
        /** @description Resource not found */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": {
                    /**
                     * Format: uri
                     * @description URI reference identifying the problem type.
                     */
                    type?: string;
                    /** @description Short human-readable summary. */
                    title?: string;
                    /** @description HTTP status code. */
                    status?: number;
                    /** @description Human-readable explanation specific to this occurrence. */
                    detail?: string;
                    /**
                     * Format: uri
                     * @description URI reference identifying this occurrence.
                     */
                    instance?: string;
                    /** @description Optional machine-readable error code from the gateway. */
                    code?: string;
                } & {
                    [key: string]: unknown;
                };
                "application/json": {
                    /**
                     * Format: uri
                     * @description URI reference identifying the problem type.
                     */
                    type?: string;
                    /** @description Short human-readable summary. */
                    title?: string;
                    /** @description HTTP status code. */
                    status?: number;
                    /** @description Human-readable explanation specific to this occurrence. */
                    detail?: string;
                    /**
                     * Format: uri
                     * @description URI reference identifying this occurrence.
                     */
                    instance?: string;
                    /** @description Optional machine-readable error code from the gateway. */
                    code?: string;
                } & {
                    [key: string]: unknown;
                };
            };
        };
    };
    parameters: {
        /** @description Opaque keyset cursor from the previous page. */
        Cursor: string;
        /** @description Page size. */
        Limit: number;
        /**
         * @description Client-supplied key for safe retries on mutating POSTs (≤128 chars).
         *     Replay with the same key and body returns the original result; different
         *     body with the same key yields 409.
         */
        IdempotencyKey: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    listEvents: {
        parameters: {
            query?: {
                /** @description Opaque keyset cursor from the previous page. */
                cursor?: string;
                /** @description Page size. */
                limit?: number;
                customerId?: string;
                purpose?: "help" | "protect";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Event list */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: {
                            items: {
                                eventId: string;
                                /** @description Bank customer identifier (opaque to Aegora). */
                                customerId: string;
                                /**
                                 * @description Declared processing purpose (help vs protect). Required before an action may fire.
                                 * @enum {string}
                                 */
                                purpose: "help" | "protect";
                                /** @enum {string} */
                                eventType: "cardAuthorisation" | "appSession" | "transaction" | "networkFlow" | "consentChange";
                                /** Format: date-time */
                                occurredAt: string;
                                /** @description Channel-safe payload. Network packet dumps are not stored here. */
                                payload?: {
                                    [key: string]: unknown;
                                };
                                /** Format: date-time */
                                createdAt: string;
                                /** Format: date-time */
                                updatedAt?: string;
                            }[];
                        };
                        meta?: {
                            /**
                             * Format: uuid
                             * @description Correlation id for this HTTP request.
                             */
                            requestId?: string;
                            /** @description Optional end-to-end correlation id. */
                            correlationId?: string;
                            /**
                             * Format: date-time
                             * @description Server time when the payload was produced.
                             */
                            generatedAt?: string;
                        };
                    };
                };
            };
            /** @description Missing or invalid API key */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        /**
                         * Format: uri
                         * @description URI reference identifying the problem type.
                         */
                        type?: string;
                        /** @description Short human-readable summary. */
                        title?: string;
                        /** @description HTTP status code. */
                        status?: number;
                        /** @description Human-readable explanation specific to this occurrence. */
                        detail?: string;
                        /**
                         * Format: uri
                         * @description URI reference identifying this occurrence.
                         */
                        instance?: string;
                        /** @description Optional machine-readable error code from the gateway. */
                        code?: string;
                    } & {
                        [key: string]: unknown;
                    };
                    "application/json": {
                        /**
                         * Format: uri
                         * @description URI reference identifying the problem type.
                         */
                        type?: string;
                        /** @description Short human-readable summary. */
                        title?: string;
                        /** @description HTTP status code. */
                        status?: number;
                        /** @description Human-readable explanation specific to this occurrence. */
                        detail?: string;
                        /**
                         * Format: uri
                         * @description URI reference identifying this occurrence.
                         */
                        instance?: string;
                        /** @description Optional machine-readable error code from the gateway. */
                        code?: string;
                    } & {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Error (RFC 7807 Problem Details) */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        /**
                         * Format: uri
                         * @description URI reference identifying the problem type.
                         */
                        type?: string;
                        /** @description Short human-readable summary. */
                        title?: string;
                        /** @description HTTP status code. */
                        status?: number;
                        /** @description Human-readable explanation specific to this occurrence. */
                        detail?: string;
                        /**
                         * Format: uri
                         * @description URI reference identifying this occurrence.
                         */
                        instance?: string;
                        /** @description Optional machine-readable error code from the gateway. */
                        code?: string;
                    } & {
                        [key: string]: unknown;
                    };
                    "application/json": {
                        /**
                         * Format: uri
                         * @description URI reference identifying the problem type.
                         */
                        type?: string;
                        /** @description Short human-readable summary. */
                        title?: string;
                        /** @description HTTP status code. */
                        status?: number;
                        /** @description Human-readable explanation specific to this occurrence. */
                        detail?: string;
                        /**
                         * Format: uri
                         * @description URI reference identifying this occurrence.
                         */
                        instance?: string;
                        /** @description Optional machine-readable error code from the gateway. */
                        code?: string;
                    } & {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    ingestEvent: {
        parameters: {
            query?: never;
            header: {
                /**
                 * @description Client-supplied key for safe retries on mutating POSTs (≤128 chars).
                 *     Replay with the same key and body returns the original result; different
                 *     body with the same key yields 409.
                 */
                "Idempotency-Key": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @description Bank customer identifier (opaque to Aegora). */
                    customerId: string;
                    /**
                     * @description Declared processing purpose (help vs protect). Required before an action may fire.
                     * @enum {string}
                     */
                    purpose: "help" | "protect";
                    /** @enum {string} */
                    eventType: "cardAuthorisation" | "appSession" | "transaction" | "networkFlow" | "consentChange";
                    /** Format: date-time */
                    occurredAt: string;
                    payload?: {
                        [key: string]: unknown;
                    };
                };
            };
        };
        responses: {
            /** @description Accepted */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: {
                            eventId: string;
                            /** @description Bank customer identifier (opaque to Aegora). */
                            customerId: string;
                            /**
                             * @description Declared processing purpose (help vs protect). Required before an action may fire.
                             * @enum {string}
                             */
                            purpose: "help" | "protect";
                            /** @enum {string} */
                            eventType: "cardAuthorisation" | "appSession" | "transaction" | "networkFlow" | "consentChange";
                            /** Format: date-time */
                            occurredAt: string;
                            /** @description Channel-safe payload. Network packet dumps are not stored here. */
                            payload?: {
                                [key: string]: unknown;
                            };
                            /** Format: date-time */
                            createdAt: string;
                            /** Format: date-time */
                            updatedAt?: string;
                        };
                        meta?: {
                            /**
                             * Format: uuid
                             * @description Correlation id for this HTTP request.
                             */
                            requestId?: string;
                            /** @description Optional end-to-end correlation id. */
                            correlationId?: string;
                            /**
                             * Format: date-time
                             * @description Server time when the payload was produced.
                             */
                            generatedAt?: string;
                        };
                    };
                };
            };
            /** @description Missing or invalid API key */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        /**
                         * Format: uri
                         * @description URI reference identifying the problem type.
                         */
                        type?: string;
                        /** @description Short human-readable summary. */
                        title?: string;
                        /** @description HTTP status code. */
                        status?: number;
                        /** @description Human-readable explanation specific to this occurrence. */
                        detail?: string;
                        /**
                         * Format: uri
                         * @description URI reference identifying this occurrence.
                         */
                        instance?: string;
                        /** @description Optional machine-readable error code from the gateway. */
                        code?: string;
                    } & {
                        [key: string]: unknown;
                    };
                    "application/json": {
                        /**
                         * Format: uri
                         * @description URI reference identifying the problem type.
                         */
                        type?: string;
                        /** @description Short human-readable summary. */
                        title?: string;
                        /** @description HTTP status code. */
                        status?: number;
                        /** @description Human-readable explanation specific to this occurrence. */
                        detail?: string;
                        /**
                         * Format: uri
                         * @description URI reference identifying this occurrence.
                         */
                        instance?: string;
                        /** @description Optional machine-readable error code from the gateway. */
                        code?: string;
                    } & {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Semantically invalid request (e.g. PACK_EMPTY) */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        /**
                         * Format: uri
                         * @description URI reference identifying the problem type.
                         */
                        type?: string;
                        /** @description Short human-readable summary. */
                        title?: string;
                        /** @description HTTP status code. */
                        status?: number;
                        /** @description Human-readable explanation specific to this occurrence. */
                        detail?: string;
                        /**
                         * Format: uri
                         * @description URI reference identifying this occurrence.
                         */
                        instance?: string;
                        /** @description Optional machine-readable error code from the gateway. */
                        code?: string;
                    } & {
                        [key: string]: unknown;
                    };
                    "application/json": {
                        /**
                         * Format: uri
                         * @description URI reference identifying the problem type.
                         */
                        type?: string;
                        /** @description Short human-readable summary. */
                        title?: string;
                        /** @description HTTP status code. */
                        status?: number;
                        /** @description Human-readable explanation specific to this occurrence. */
                        detail?: string;
                        /**
                         * Format: uri
                         * @description URI reference identifying this occurrence.
                         */
                        instance?: string;
                        /** @description Optional machine-readable error code from the gateway. */
                        code?: string;
                    } & {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Error (RFC 7807 Problem Details) */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        /**
                         * Format: uri
                         * @description URI reference identifying the problem type.
                         */
                        type?: string;
                        /** @description Short human-readable summary. */
                        title?: string;
                        /** @description HTTP status code. */
                        status?: number;
                        /** @description Human-readable explanation specific to this occurrence. */
                        detail?: string;
                        /**
                         * Format: uri
                         * @description URI reference identifying this occurrence.
                         */
                        instance?: string;
                        /** @description Optional machine-readable error code from the gateway. */
                        code?: string;
                    } & {
                        [key: string]: unknown;
                    };
                    "application/json": {
                        /**
                         * Format: uri
                         * @description URI reference identifying the problem type.
                         */
                        type?: string;
                        /** @description Short human-readable summary. */
                        title?: string;
                        /** @description HTTP status code. */
                        status?: number;
                        /** @description Human-readable explanation specific to this occurrence. */
                        detail?: string;
                        /**
                         * Format: uri
                         * @description URI reference identifying this occurrence.
                         */
                        instance?: string;
                        /** @description Optional machine-readable error code from the gateway. */
                        code?: string;
                    } & {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    getEvent: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                eventId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Event */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: {
                            eventId: string;
                            /** @description Bank customer identifier (opaque to Aegora). */
                            customerId: string;
                            /**
                             * @description Declared processing purpose (help vs protect). Required before an action may fire.
                             * @enum {string}
                             */
                            purpose: "help" | "protect";
                            /** @enum {string} */
                            eventType: "cardAuthorisation" | "appSession" | "transaction" | "networkFlow" | "consentChange";
                            /** Format: date-time */
                            occurredAt: string;
                            /** @description Channel-safe payload. Network packet dumps are not stored here. */
                            payload?: {
                                [key: string]: unknown;
                            };
                            /** Format: date-time */
                            createdAt: string;
                            /** Format: date-time */
                            updatedAt?: string;
                        };
                        meta?: {
                            /**
                             * Format: uuid
                             * @description Correlation id for this HTTP request.
                             */
                            requestId?: string;
                            /** @description Optional end-to-end correlation id. */
                            correlationId?: string;
                            /**
                             * Format: date-time
                             * @description Server time when the payload was produced.
                             */
                            generatedAt?: string;
                        };
                    };
                };
            };
            /** @description Missing or invalid API key */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        /**
                         * Format: uri
                         * @description URI reference identifying the problem type.
                         */
                        type?: string;
                        /** @description Short human-readable summary. */
                        title?: string;
                        /** @description HTTP status code. */
                        status?: number;
                        /** @description Human-readable explanation specific to this occurrence. */
                        detail?: string;
                        /**
                         * Format: uri
                         * @description URI reference identifying this occurrence.
                         */
                        instance?: string;
                        /** @description Optional machine-readable error code from the gateway. */
                        code?: string;
                    } & {
                        [key: string]: unknown;
                    };
                    "application/json": {
                        /**
                         * Format: uri
                         * @description URI reference identifying the problem type.
                         */
                        type?: string;
                        /** @description Short human-readable summary. */
                        title?: string;
                        /** @description HTTP status code. */
                        status?: number;
                        /** @description Human-readable explanation specific to this occurrence. */
                        detail?: string;
                        /**
                         * Format: uri
                         * @description URI reference identifying this occurrence.
                         */
                        instance?: string;
                        /** @description Optional machine-readable error code from the gateway. */
                        code?: string;
                    } & {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Resource not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        /**
                         * Format: uri
                         * @description URI reference identifying the problem type.
                         */
                        type?: string;
                        /** @description Short human-readable summary. */
                        title?: string;
                        /** @description HTTP status code. */
                        status?: number;
                        /** @description Human-readable explanation specific to this occurrence. */
                        detail?: string;
                        /**
                         * Format: uri
                         * @description URI reference identifying this occurrence.
                         */
                        instance?: string;
                        /** @description Optional machine-readable error code from the gateway. */
                        code?: string;
                    } & {
                        [key: string]: unknown;
                    };
                    "application/json": {
                        /**
                         * Format: uri
                         * @description URI reference identifying the problem type.
                         */
                        type?: string;
                        /** @description Short human-readable summary. */
                        title?: string;
                        /** @description HTTP status code. */
                        status?: number;
                        /** @description Human-readable explanation specific to this occurrence. */
                        detail?: string;
                        /**
                         * Format: uri
                         * @description URI reference identifying this occurrence.
                         */
                        instance?: string;
                        /** @description Optional machine-readable error code from the gateway. */
                        code?: string;
                    } & {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Error (RFC 7807 Problem Details) */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        /**
                         * Format: uri
                         * @description URI reference identifying the problem type.
                         */
                        type?: string;
                        /** @description Short human-readable summary. */
                        title?: string;
                        /** @description HTTP status code. */
                        status?: number;
                        /** @description Human-readable explanation specific to this occurrence. */
                        detail?: string;
                        /**
                         * Format: uri
                         * @description URI reference identifying this occurrence.
                         */
                        instance?: string;
                        /** @description Optional machine-readable error code from the gateway. */
                        code?: string;
                    } & {
                        [key: string]: unknown;
                    };
                    "application/json": {
                        /**
                         * Format: uri
                         * @description URI reference identifying the problem type.
                         */
                        type?: string;
                        /** @description Short human-readable summary. */
                        title?: string;
                        /** @description HTTP status code. */
                        status?: number;
                        /** @description Human-readable explanation specific to this occurrence. */
                        detail?: string;
                        /**
                         * Format: uri
                         * @description URI reference identifying this occurrence.
                         */
                        instance?: string;
                        /** @description Optional machine-readable error code from the gateway. */
                        code?: string;
                    } & {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
}
