/**
 * Handlers for Dispute
 *
 * Generated by Handler Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: holds
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyRequest, FastifyReply } from "fastify";
import type { HoldsDomainModule } from "../dependencies/holds-ddd.dependencies.js";
import type { CreateHoldDisputeInput, ListHoldDisputesInput } from "@aegora/services/holds";
// Use cases are available via deps.useCases.<repoKey>.<verb>
// Execution context is automatically set up by route wrapper (wrapHandlerInExecutionContext)

/**
 * Handler for GET /v1/holds/{holdId}/disputes
 * Operation: listHoldDisputes
 */
export async function listHoldDisputes(
  request: FastifyRequest<{ Params: { holdId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>,
  reply: FastifyReply,
  deps: HoldsDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: ListHoldDisputesInput = {
    holdId: request.params.holdId,
  };
  const result = await deps.useCases.disputes.list.execute(input);
  return reply.code(200).send(result);
}


/**
 * Handler for POST /v1/holds/{holdId}/disputes
 * Operation: createHoldDispute
 */
export async function createHoldDispute(
  request: FastifyRequest<{ Params: { holdId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>,
  reply: FastifyReply,
  deps: HoldsDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: CreateHoldDisputeInput = {
    holdId: request.params.holdId,
    ...(request.body ?? {}),
  };
  const result = await deps.useCases.disputes.create.execute(input);
  return reply.code(201).send(result);
}


