/**
 * Handlers for Hold
 *
 * Generated by Handler Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: holds
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyRequest, FastifyReply } from "fastify";
import type { HoldsDomainModule } from "../dependencies/holds-ddd.dependencies.js";
import type { CreateHoldInput, GetHoldInput, ListHoldsInput } from "@aegora/services/holds";
// Use cases are available via deps.useCases.<repoKey>.<verb>
// Execution context is automatically set up by route wrapper (wrapHandlerInExecutionContext)

/**
 * Handler for GET /v1/holds
 * Operation: listHolds
 */
export async function listHolds(
  request: FastifyRequest<{ Params: Record<string, string>; Querystring: { cursor?: string | string[], limit?: string | string[], customerId?: string | string[], status?: string | string[] }; Body: unknown }>,
  reply: FastifyReply,
  deps: HoldsDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: ListHoldsInput = {
    ...(request.query ?? {}),
  };
  const result = await deps.useCases.holds.list.execute(input);
  return reply.code(200).send(result);
}


/**
 * Handler for POST /v1/holds
 * Operation: createHold
 */
export async function createHold(
  request: FastifyRequest,
  reply: FastifyReply,
  deps: HoldsDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: CreateHoldInput = {
    ...(request.body ?? {}),
  };
  const result = await deps.useCases.holds.create.execute(input);
  return reply.code(201).send(result);
}


/**
 * Handler for GET /v1/holds/{holdId}
 * Operation: getHold
 */
export async function getHold(
  request: FastifyRequest<{ Params: { holdId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>,
  reply: FastifyReply,
  deps: HoldsDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: GetHoldInput = {
    holdId: request.params.holdId,
  };
  const result = await deps.useCases.holds.get.execute(input);
  return reply.code(200).send(result);
}


