/**
 * Handlers for Deliver
 *
 * Generated by Handler Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: offers
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyRequest, FastifyReply } from "fastify";
import type { OffersDomainModule } from "../dependencies/offers-ddd.dependencies.js";
import type { DeliverOfferInput } from "@aegora/services/offers";
// Use cases are available via deps.useCases.<repoKey>.<verb>
// Execution context is automatically set up by route wrapper (wrapHandlerInExecutionContext)

/**
 * Handler for POST /v1/offers/{offerId}/deliver
 * Operation: deliverOffer
 */
export async function deliverOffer(
  request: FastifyRequest<{ Params: { offerId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>,
  reply: FastifyReply,
  deps: OffersDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: DeliverOfferInput = {
    offerId: request.params.offerId,
    ...(request.body ?? {}),
  };
  const result = await deps.useCases.delivers.get.execute(input);
  return reply.code(200).send(result);
}


