/**
 * Factories barrel export
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: offers
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


/**
 * Factories Barrel Export
 *
 * Exports all entity and DTO factories for the offers domain.
 * Use these factories in tests to create test data.
 */

export { createConsentRecord } from "./consent-record/entity/consent-record.entity.factory.js";
export { createCreateBlockRequest } from "./block/dto/create-block.dto.factory.js";
export { createOffer } from "./offer/entity/offer.entity.factory.js";
export { createOverride } from "./override/entity/override.entity.factory.js";
