/**
 * EventRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: events
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * EventRepository Port
 *
 * DDD: Application port for eventrepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { GetEventInput, GetEventOutput, IngestEventInput, IngestEventOutput, ListEventsInput, ListEventsOutput } from "../dto/event.dto";
export interface EventRepository {
  listEvents(input: ListEventsInput): Promise<ListEventsOutput>;
  ingestEvent(input: IngestEventInput): Promise<IngestEventOutput>;
  getEvent(input: GetEventInput): Promise<GetEventOutput>;
}

export type { GetEventInput, GetEventOutput, IngestEventInput, IngestEventOutput, ListEventsInput, ListEventsOutput } from "../dto/event.dto";
