/**
 * SuppressRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: alerts
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * SuppressRepository Port
 *
 * DDD: Application port for suppressrepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { SuppressAlertInput, SuppressAlertOutput } from "../dto/suppress.dto";
export interface SuppressRepository {
  suppressAlert(input: SuppressAlertInput): Promise<SuppressAlertOutput>;
}

export type { SuppressAlertInput, SuppressAlertOutput } from "../dto/suppress.dto";
