/**
 * Deliver DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: offers
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Deliver DTOs
 *
 * DDD: Application DTOs for Deliver use cases.
 */

import type { DeliverOfferParams, DeliverOfferRequestInput } from "@aegora/core/offers/types";

export type DeliverOfferInput = DeliverOfferParams & DeliverOfferRequestInput;

export type DeliverOfferOutput = {};
