/**
 * Override DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: offers
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Override DTOs
 *
 * DDD: Application DTOs for Override use cases.
 */

import type { ListOfferOverridesParams, OverrideOfferParams, OverrideOfferRequestInput } from "@aegora/core/offers/types";

export type ListOfferOverridesInput = ListOfferOverridesParams;

export type OverrideOfferInput = OverrideOfferParams & OverrideOfferRequestInput;

export type ListOfferOverridesOutput = {};

export type OverrideOfferOutput = {};
