/**
 * Handlers for Case
 *
 * Generated by Handler Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: cases
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyRequest, FastifyReply } from "fastify";
import type { CasesDomainModule } from "../dependencies/cases-ddd.dependencies.js";
import type { GetCaseInput, ListCasesInput, OpenCaseInput } from "@aegora/services/cases";
// Use cases are available via deps.useCases.<repoKey>.<verb>
// Execution context is automatically set up by route wrapper (wrapHandlerInExecutionContext)

/**
 * Handler for GET /v1/cases
 * Operation: listCases
 */
export async function listCases(
  request: FastifyRequest<{ Params: Record<string, string>; Querystring: { cursor?: string | string[], limit?: string | string[], status?: string | string[] }; Body: unknown }>,
  reply: FastifyReply,
  deps: CasesDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: ListCasesInput = {
    ...(request.query ?? {}),
  };
  const result = await deps.useCases.cases.list.execute(input);
  return reply.code(200).send(result);
}


/**
 * Handler for POST /v1/cases
 * Operation: openCase
 */
export async function openCase(
  request: FastifyRequest,
  reply: FastifyReply,
  deps: CasesDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: OpenCaseInput = {
    ...(request.body ?? {}),
  };
  const result = await deps.useCases.cases.get.execute(input);
  return reply.code(201).send(result);
}


/**
 * Handler for GET /v1/cases/{caseId}
 * Operation: getCase
 */
export async function getCase(
  request: FastifyRequest<{ Params: { caseId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>,
  reply: FastifyReply,
  deps: CasesDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: GetCaseInput = {
    caseId: request.params.caseId,
  };
  const result = await deps.useCases.cases.get.execute(input);
  return reply.code(200).send(result);
}


