/**
 * Routes for Case
 *
 * Generated by Routes Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: cases
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyInstance, FastifyRequest, FastifyReply } from "fastify";
import { getDependencyContainer } from "../../../infrastructure/dependency-container.js";
import { getCase, listCases, openCase } from "../handlers/case.handlers.js";
import { wrapHandlerInExecutionContext } from "../../../lib/execution-context-wrapper.js";

// Fastify types are available globally
export async function caseRoutes(fastify: FastifyInstance) {
  // GET /v1/cases (unscoped; scope set for security middleware)
  fastify.get(
    "/v1/cases",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: Record<string, string>; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getCasesDependenciesForRequest();
        await listCases(request, reply, deps);
      });
    }
  );


  // POST /v1/cases (unscoped; scope set for security middleware)
  fastify.post(
    "/v1/cases",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: Record<string, string>; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getCasesDependenciesForRequest();
        await openCase(request, reply, deps);
      });
    }
  );


  // GET /v1/cases/{caseId} (unscoped; scope set for security middleware)
  fastify.get(
    "/v1/cases/:caseId",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: { caseId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getCasesDependenciesForRequest();
        await getCase(request, reply, deps);
      });
    }
  );


}
