/**
 * Routes for Block
 *
 * Generated by Routes Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: offers
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyInstance, FastifyRequest, FastifyReply } from "fastify";
import { getDependencyContainer } from "../../../infrastructure/dependency-container.js";
import { blockOffer } from "../handlers/block.handlers.js";
import { wrapHandlerInExecutionContext } from "../../../lib/execution-context-wrapper.js";

// Fastify types are available globally
export async function blockRoutes(fastify: FastifyInstance) {
  // POST /v1/offers/{offerId}/block (unscoped; scope set for security middleware)
  fastify.post(
    "/v1/offers/:offerId/block",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: { offerId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getOffersDependenciesForRequest();
        await blockOffer(request, reply, deps);
      });
    }
  );


}
