/**
 * ListPolicies handler tests
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: policies
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { describe, it, expect, beforeEach, vi } from "vitest";
import { listPolicies } from "@aegora/api-server/domains/policies/handlers";
import type { PoliciesDDDDependencies } from "@aegora/api-server/domains/policies";
import { createMockRequest, createMockReply, createMockDependencies, TEST_ORG_ID } from "@aegora/tests/shared";
import { POLICIES_USE_CASES } from "../__factories__/use-cases.js";

describe("ListPolicies", () => {
  let mockRequest: ReturnType<typeof createMockRequest>;
  let mockReply: ReturnType<typeof createMockReply>;
  let mockDeps: PoliciesDDDDependencies;
  const orgId = TEST_ORG_ID;

  beforeEach(() => {
    mockRequest = createMockRequest({ orgId });
    mockReply = createMockReply();
    mockDeps = createMockDependencies<PoliciesDDDDependencies>(
      POLICIES_USE_CASES,
      {
        // Mock use case dependencies here
      }
    );
  });

  it("should return 200 with list of entities", async () => {
    const entities = [
      { id: 'mock-1', orgId } as any,
      { id: 'mock-2', orgId } as any,
    ];
    const useCaseResult = {
      data: { items: entities, nextCursor: undefined, prevCursor: undefined },
      meta: { correlationId: "test", timestamp: new Date().toISOString(), pagination: {} }
    };
    
    vi.spyOn(mockDeps.executeListPolicies, "execute").mockResolvedValue(useCaseResult);

    await listPolicies(mockRequest, mockReply, mockDeps);

    expect(mockDeps.executeListPolicies.execute).toHaveBeenCalledWith(expect.anything());
    expect(mockReply.code).toHaveBeenCalledWith(200);
    expect(mockReply.send).toHaveBeenCalledWith(useCaseResult);
  });

});
