/**
 * Escalate DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: alerts
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Escalate DTOs
 *
 * DDD: Application DTOs for Escalate use cases.
 */

import type { EscalateAlertParams, EscalateAlertRequestInput } from "@aegora/core/alerts/types";

export type EscalateAlertInput = EscalateAlertParams & EscalateAlertRequestInput;

export type EscalateAlertOutput = {};
