/**
 * Suppress DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: alerts
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Suppress DTOs
 *
 * DDD: Application DTOs for Suppress use cases.
 */

import type { SuppressAlertParams, SuppressAlertRequestInput } from "@aegora/core/alerts/types";

export type SuppressAlertInput = SuppressAlertParams & SuppressAlertRequestInput;

export type SuppressAlertOutput = {};
