/**
 * BlockOffer handler tests
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: offers
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { describe, it, expect, beforeEach, vi } from "vitest";
import { blockOffer } from "@aegora/api-server/domains/offers/handlers";
import type { OffersDDDDependencies } from "@aegora/api-server/domains/offers";
import { createCreateBlockRequest } from "@aegora/factories/offers";
import { createMockRequest, createMockReply, createMockDependencies, TEST_ORG_ID } from "@aegora/tests/shared";
import { OFFERS_USE_CASES } from "../__factories__/use-cases.js";

describe("BlockOffer", () => {
  let mockRequest: ReturnType<typeof createMockRequest>;
  let mockReply: ReturnType<typeof createMockReply>;
  let mockDeps: OffersDDDDependencies;
  const orgId = TEST_ORG_ID;

  beforeEach(() => {
    mockRequest = createMockRequest({ orgId });
    mockReply = createMockReply();
    mockDeps = createMockDependencies<OffersDDDDependencies>(
      OFFERS_USE_CASES,
      {
        // Mock use case dependencies here
      }
    );
  });

  it("should return 201 with created entity", async () => {
    const input = createCreateBlockRequest();
    const entity = { id: 'mock-id', orgId } as any;
    const useCaseResult = { data: entity, meta: { correlationId: "test", timestamp: new Date().toISOString() } };
    
    mockRequest.body = input;
    vi.spyOn(mockDeps.executeBlockOffer, "execute").mockResolvedValue(useCaseResult);

    await blockOffer(mockRequest, mockReply, mockDeps);

    expect(mockDeps.executeBlockOffer.execute).toHaveBeenCalledWith(expect.anything());
    expect(mockReply.code).toHaveBeenCalledWith(200);
    expect(mockReply.send).toHaveBeenCalledWith(useCaseResult);
  });

});
